[package]
name = "seekdeep-code-runtime-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
seekdeep-lossless-json = { path = "../../lossless-json" }
anyhow.workspace = true
regress = { workspace = true, features = ["utf16"] }
js-sys.workspace = true
ryu-js.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true

[lints]
workspace = true
