[package]
name = "seekdeep-spill"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
seekdeep-cordis = { path = "../cordis" }
seekdeep-core = { path = "../core" }
seekdeep-invariants = { path = "../invariants" }
seekdeep-llm = { path = "../llm" }
seekdeep-util = { path = "../util" }

[dev-dependencies]
parking_lot.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
