//! Compiled Host Typert artifacts.
//!
//! Source: each package with a `./typert` export ships a generated `typert.host.js` whose
//! `TYPERT` contribution carries strict Zod codecs for every Remote boundary. The Rust port
//! embeds the same `FaceModel` slice (`typert.host.json`, generated by `cargo xtask
//! typert-host-artifacts` from the pinned Host face model) and interprets it at the boundary:
//! [`ModelSchema`] accepts exactly the values the generated Zod schema accepts and returns the
//! same stripped value, so the typert gateway reports the source's boundary diagnostics.

use std::{
    collections::{BTreeMap, HashMap},
    sync::Arc,
};

use seekdeep_cordis::{Context, fiber::EffectHandle};
use seekdeep_typert_loader::{TYPERT_ARTIFACTS, TypertPackageArtifact};
use seekdeep_typert_model::{
    ComputedMember, DeclarationKind, DefinedTypeNode, InvocationModel,
    InvocationParameterSource as ModelParameterSource, InvocationTarget, KeywordTypeName,
    LiteralValue, MemberKind, MemberModel, MemberVisibility, RemoteBoundaryModel, SymbolId,
    TypeDeclarationModel, TypeGraph, TypeNodeId, TypeNodeKind, TypeNodeModel, TypeParameterId,
    TypeTargetModel,
};
use seekdeep_typert_protocol::{
    InvocationDescriptor, InvocationParameterDescriptor, InvocationParameterSource,
    InvocationReceiver, InvocationScope, InvocationSourceLocation, TypertBoundaryValue,
    TypertCodec, TypertSchema,
};
use seekdeep_typert_registry::{TypertContribution, TypertFace, TypertPackageModel};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value, json};

/// One package's embedded Host artifact: the generated runtime model, its Remote invocations,
/// and the type-graph slice their boundaries reach.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostArtifact {
    /// Exact package name.
    pub package: String,
    /// Always `host`.
    pub face: String,
    /// The `TYPERT.model` runtime section (services, events, objects).
    pub model: Value,
    /// Remote invocations in source order.
    pub invocations: Vec<InvocationModel>,
    /// Declarations and type nodes reachable from the invocation boundaries.
    pub graph: TypeGraph,
}

/// Parses one embedded artifact document.
///
/// # Errors
///
/// Returns when the document is not a Host artifact.
pub fn parse(json: &str) -> anyhow::Result<HostArtifact> {
    let artifact: HostArtifact = serde_json::from_str(json)?;
    anyhow::ensure!(
        artifact.face == "host",
        "typert host artifact for {} has face {:?}",
        artifact.package,
        artifact.face
    );
    Ok(artifact)
}

/// Builds the registry contribution of one embedded artifact.
///
/// # Errors
///
/// Returns parse failures or a boundary whose type the model cannot project.
pub fn contribution(json: &str) -> anyhow::Result<TypertContribution> {
    let artifact = parse(json)?;
    let model: TypertPackageModel = serde_json::from_value(artifact.model.clone())?;
    let graph = Arc::new(Model::new(&artifact.graph));
    let invocations = artifact
        .invocations
        .iter()
        .map(|invocation| descriptor(&graph, invocation))
        .collect::<anyhow::Result<Vec<_>>>()?;
    Ok(TypertContribution {
        package: artifact.package,
        face: TypertFace::Host,
        schemas: Vec::new(),
        model,
        invocations,
    })
}

/// Registers one package's embedded artifact with the Host artifact directory, so the typert
/// loader mounts its strict contribution while the package is live.
///
/// # Errors
///
/// Returns when the artifact directory is absent or the package is already registered.
pub fn register(context: &Context, json: &'static str) -> anyhow::Result<EffectHandle> {
    let artifact = parse(json)?;
    // Source: a package's `./typert` export is consumed only where the typert loader is
    // composed; without an artifact directory the package still loads.
    let Some(registry) = context.get(TYPERT_ARTIFACTS) else {
        return Ok(EffectHandle::synchronous(
            format!(
                "typert host artifact {} (no artifact directory)",
                artifact.package
            ),
            || Ok(()),
        ));
    };
    // Source: the artifact is a static package export resolved when the module loads, so the
    // loader's activation pass finds it before the plugin applies. A host that registers its
    // shipped artifacts at load (`profile_boot`) keeps that ordering; apply-time registration
    // then stays a no-op instead of a duplicate.
    if registry.contains(&artifact.package) {
        return Ok(EffectHandle::synchronous(
            format!(
                "typert host artifact {} (registered at load)",
                artifact.package
            ),
            || Ok(()),
        ));
    }
    registry.register(
        context,
        TypertPackageArtifact {
            package: artifact.package,
            host: Some(Arc::new(move || {
                Box::pin(async move { contribution(json) })
            })),
        },
    )
}

fn descriptor(
    model: &Arc<Model>,
    invocation: &InvocationModel,
) -> anyhow::Result<InvocationDescriptor> {
    let strict = |boundary: &RemoteBoundaryModel| -> anyhow::Result<TypertCodec> {
        let schema = ModelSchema {
            model: model.clone(),
            root: boundary.codec_type.clone(),
            accepts_undefined: boundary.accepts_undefined,
        };
        schema.check()?;
        Ok(TypertCodec::Strict {
            type_symbol: boundary.type_symbol.as_str().to_owned(),
            schema: Arc::new(schema),
        })
    };
    Ok(InvocationDescriptor {
        id: invocation.id.as_str().to_owned(),
        service: invocation.service.clone(),
        namespace: invocation.namespace.clone(),
        method: invocation.method.clone(),
        implementation: invocation.implementation.clone(),
        invocation: match &invocation.invocation {
            InvocationTarget::Direct => InvocationReceiver::Direct,
            InvocationTarget::Context {
                context,
                wire,
                boundary,
            } => InvocationReceiver::Context {
                context: context.clone(),
                wire: wire.clone(),
                codec: strict(boundary)?,
            },
        },
        scope: invocation.scope.as_ref().map(|scope| InvocationScope {
            context: scope.context.clone(),
            wire: scope.wire.clone(),
        }),
        parameters: invocation
            .parameters
            .iter()
            .map(|parameter| {
                Ok(InvocationParameterDescriptor {
                    name: parameter.name.clone(),
                    wire: parameter.wire.clone(),
                    source: match parameter.source {
                        ModelParameterSource::Json => InvocationParameterSource::Json,
                        ModelParameterSource::Lookup => InvocationParameterSource::Lookup,
                    },
                    lookup: parameter.lookup.clone(),
                    codec: strict(&parameter.boundary)?,
                    accepts_undefined: parameter.boundary.accepts_undefined.then_some(true),
                })
            })
            .collect::<anyhow::Result<Vec<_>>>()?,
        cancellation: invocation.cancellation.is_some(),
        result: strict(&invocation.result)?,
        source_location: Some(InvocationSourceLocation {
            file: invocation.location.file.clone(),
            line: invocation.location.line as u64,
            column: invocation.location.column as u64,
        }),
    })
}

/// The indexed type graph one artifact's schemas walk.
#[derive(Debug)]
struct Model {
    nodes: HashMap<TypeNodeId, DefinedTypeNode>,
    declarations: HashMap<SymbolId, TypeDeclarationModel>,
}

impl Model {
    fn new(graph: &TypeGraph) -> Self {
        Self {
            nodes: graph
                .nodes
                .iter()
                .filter_map(|node| match node {
                    TypeNodeModel::Defined(node) => Some((node.id.clone(), node.clone())),
                    TypeNodeModel::Unsupported(_) => None,
                })
                .collect(),
            declarations: graph
                .declarations
                .iter()
                .map(|declaration| (declaration.id.clone(), declaration.clone()))
                .collect(),
        }
    }

    fn node(&self, id: &TypeNodeId) -> Result<&DefinedTypeNode, String> {
        self.nodes
            .get(id)
            .ok_or_else(|| format!("type node {} is outside the artifact graph", id.as_str()))
    }

    fn declaration(&self, symbol: &SymbolId) -> Result<&TypeDeclarationModel, String> {
        self.declarations.get(symbol).ok_or_else(|| {
            format!(
                "declaration {} is outside the artifact graph",
                symbol.as_str()
            )
        })
    }
}

/// Type-parameter bindings: each bound parameter names a node plus the bindings it was bound
/// under (the generator's substitution map, resolved lazily here).
#[derive(Clone, Debug, Default)]
struct Bindings(BTreeMap<TypeParameterId, (TypeNodeId, Box<Bindings>)>);

/// A strict boundary codec interpreting the generated Zod projection of one type node.
#[derive(Debug)]
pub struct ModelSchema {
    model: Arc<Model>,
    root: TypeNodeId,
    accepts_undefined: bool,
}

impl ModelSchema {
    /// Fails at artifact load when the boundary type has no Zod projection, exactly where the
    /// generator would have refused to emit the source artifact.
    fn check(&self) -> anyhow::Result<()> {
        let mut seen = Vec::new();
        self.project(&self.root, &Bindings::default(), &mut seen)
            .map(|_| ())
            .map_err(|reason| anyhow::anyhow!("{}: {reason}", self.root.as_str()))
    }

    fn validate(
        &self,
        id: &TypeNodeId,
        value: &Value,
        bindings: &Bindings,
    ) -> Result<Value, String> {
        let node = self.model.node(id)?;
        match &node.kind {
            TypeNodeKind::Keyword { name } => keyword(name, value),
            TypeNodeKind::Literal { value: literal, .. } => {
                if literal_matches(literal, value) {
                    Ok(value.clone())
                } else {
                    Err(format!("expected literal {}", literal_text(literal)))
                }
            }
            TypeNodeKind::Parenthesized { ty } => self.validate(ty, value, bindings),
            TypeNodeKind::Reference {
                name,
                target,
                arguments,
            } => self.validate_reference(name, target, arguments, value, bindings),
            TypeNodeKind::Union { types } => {
                if types.is_empty() {
                    return Err("never accepts no value".to_owned());
                }
                let mut failures = Vec::new();
                for member in types {
                    match self.validate(member, value, bindings) {
                        Ok(parsed) => return Ok(parsed),
                        Err(reason) => failures.push(reason),
                    }
                }
                Err(format!("no union member matched: {}", failures.join("; ")))
            }
            TypeNodeKind::Intersection { types } => {
                let mut merged = value.clone();
                for member in types {
                    let parsed = self.validate(member, value, bindings)?;
                    merged = merge(merged, parsed)?;
                }
                Ok(merged)
            }
            TypeNodeKind::Array { element } => self.validate_array(element, value, bindings),
            TypeNodeKind::Tuple { elements } => {
                let Some(items) = value.as_array() else {
                    return Err("expected a tuple".to_owned());
                };
                let fixed = elements.iter().filter(|element| !element.rest).count();
                let rest = elements.iter().find(|element| element.rest);
                let mut parsed = Vec::new();
                for (index, element) in elements.iter().filter(|element| !element.rest).enumerate()
                {
                    match items.get(index) {
                        Some(item) => parsed.push(self.validate(&element.ty, item, bindings)?),
                        None if element.optional => break,
                        None => return Err(format!("tuple element {index} is required")),
                    }
                }
                if items.len() > fixed {
                    let Some(rest) = rest else {
                        return Err("tuple has too many elements".to_owned());
                    };
                    let element = self.rest_element(&rest.ty)?;
                    for item in &items[fixed..] {
                        parsed.push(self.validate(&element, item, bindings)?);
                    }
                }
                Ok(Value::Array(parsed))
            }
            TypeNodeKind::Object { members } => self.validate_object(members, value, bindings),
            other => Err(format!("{} has no Zod projection", kind_name(other))),
        }
    }

    fn rest_element(&self, id: &TypeNodeId) -> Result<TypeNodeId, String> {
        match &self.model.node(id)?.kind {
            TypeNodeKind::Array { element } => Ok(element.clone()),
            TypeNodeKind::Reference {
                target: TypeTargetModel::Standard { name },
                arguments,
                ..
            } if matches!(name.as_str(), "Array" | "ReadonlyArray") => arguments
                .first()
                .cloned()
                .ok_or_else(|| "tuple rest array has no element type".to_owned()),
            _ => Err("tuple rest element must retain an array type".to_owned()),
        }
    }

    fn validate_array(
        &self,
        element: &TypeNodeId,
        value: &Value,
        bindings: &Bindings,
    ) -> Result<Value, String> {
        let Some(items) = value.as_array() else {
            return Err("expected an array".to_owned());
        };
        items
            .iter()
            .enumerate()
            .map(|(index, item)| {
                self.validate(element, item, bindings)
                    .map_err(|reason| format!("[{index}]: {reason}"))
            })
            .collect::<Result<Vec<_>, _>>()
            .map(Value::Array)
    }

    fn validate_reference(
        &self,
        name: &str,
        target: &TypeTargetModel,
        arguments: &[TypeNodeId],
        value: &Value,
        bindings: &Bindings,
    ) -> Result<Value, String> {
        match target {
            TypeTargetModel::Declaration { symbol } => {
                let declaration = self.model.declaration(symbol)?;
                let mut bound = Bindings::default();
                for (index, parameter) in declaration.type_parameters.iter().enumerate() {
                    let (node, under) = match arguments.get(index) {
                        Some(argument) => (argument.clone(), bindings.clone()),
                        None => match &parameter.default {
                            Some(default) => (default.clone(), bound.clone()),
                            None => {
                                return Err(format!(
                                    "{name}: missing type argument {}",
                                    parameter.name
                                ));
                            }
                        },
                    };
                    bound
                        .0
                        .insert(parameter.id.clone(), (node, Box::new(under)));
                }
                self.validate_declaration(declaration, value, &bound)
            }
            TypeTargetModel::TypeParameter { parameter } => {
                let (node, under) = bindings
                    .0
                    .get(parameter)
                    .ok_or_else(|| format!("{name}: unbound type parameter"))?;
                self.validate(node, value, under)
            }
            TypeTargetModel::Standard { name: standard } => match standard.as_str() {
                "Array" | "ReadonlyArray" => {
                    let element = arguments
                        .first()
                        .ok_or_else(|| format!("{name}: array has no element type"))?;
                    self.validate_array(element, value, bindings)
                }
                "Record" => {
                    let (Some(key), Some(item)) = (arguments.first(), arguments.get(1)) else {
                        return Err(format!("{name}: record needs key and value types"));
                    };
                    let Some(entries) = value.as_object() else {
                        return Err("expected a record".to_owned());
                    };
                    let mut parsed = Map::new();
                    for (entry_key, entry) in entries {
                        self.validate(key, &Value::String(entry_key.clone()), bindings)
                            .map_err(|reason| format!("key {entry_key:?}: {reason}"))?;
                        parsed.insert(
                            entry_key.clone(),
                            self.validate(item, entry, bindings)
                                .map_err(|reason| format!("{entry_key}: {reason}"))?,
                        );
                    }
                    Ok(Value::Object(parsed))
                }
                "Date" => Err("expected a Date instance".to_owned()),
                other => Err(format!("standard type {other} has no Zod projection")),
            },
            TypeTargetModel::CrossFace { .. } | TypeTargetModel::External { .. } => {
                Err(format!("{name}: reference outside the artifact face"))
            }
        }
    }

    fn validate_declaration(
        &self,
        declaration: &TypeDeclarationModel,
        value: &Value,
        bindings: &Bindings,
    ) -> Result<Value, String> {
        match declaration.kind {
            DeclarationKind::Enum => Err(format!(
                "{}: enums have no Zod projection",
                declaration.name
            )),
            DeclarationKind::Alias => {
                let ty = declaration
                    .ty
                    .as_ref()
                    .ok_or_else(|| format!("{}: alias has no type", declaration.name))?;
                self.validate(ty, value, bindings)
            }
            DeclarationKind::Interface | DeclarationKind::Class => {
                let mut merged = value.clone();
                for base in &declaration.extends {
                    merged = merge(merged, self.validate(base, value, bindings)?)?;
                }
                let own = self.validate_object(&declaration.members, value, bindings)?;
                merge(merged, own)
            }
        }
    }

    fn validate_object(
        &self,
        members: &[MemberModel],
        value: &Value,
        bindings: &Bindings,
    ) -> Result<Value, String> {
        let mut properties = Vec::new();
        let mut index = None;
        let mut symbols = 0;
        for member in members {
            let MemberModel::Defined(member) = member else {
                return Err("unsupported model variant".to_owned());
            };
            let base = &member.base;
            if base.is_static || base.visibility != MemberVisibility::Public {
                continue;
            }
            if base.computed == Some(ComputedMember::Symbol) {
                symbols += 1;
                continue;
            }
            if base.computed == Some(ComputedMember::Dynamic) {
                return Err(format!(
                    "computed member {} has no fixed JSON property name",
                    base.name
                ));
            }
            match &member.kind {
                MemberKind::Index { signature } => {
                    let [parameter] = signature.parameters.as_slice() else {
                        return Err(
                            "index signature must have exactly one key parameter".to_owned()
                        );
                    };
                    if index
                        .replace((parameter.ty.clone(), signature.returns.clone()))
                        .is_some()
                    {
                        return Err("object type has more than one JSON index signature".to_owned());
                    }
                }
                MemberKind::Property { ty } => properties.push((
                    base.json_name.clone().unwrap_or_else(|| base.name.clone()),
                    ty.clone(),
                    base.optional,
                )),
                other => {
                    return Err(format!(
                        "{} member {} is not data-schema projectable",
                        other.as_str(),
                        base.name
                    ));
                }
            }
        }
        if properties.is_empty() && index.is_none() && symbols > 0 {
            return Ok(value.clone());
        }
        let Some(entries) = value.as_object() else {
            return Err("expected an object".to_owned());
        };
        let mut parsed = Map::new();
        for (key, ty, optional) in &properties {
            match entries.get(key) {
                Some(entry) => {
                    parsed.insert(
                        key.clone(),
                        self.validate(ty, entry, bindings)
                            .map_err(|reason| format!("{key}: {reason}"))?,
                    );
                }
                None if *optional => {}
                None => return Err(format!("{key}: required")),
            }
        }
        if let Some((key_type, value_type)) = &index {
            for (key, entry) in entries {
                if properties.iter().any(|(name, ..)| name == key) {
                    continue;
                }
                self.validate(key_type, &Value::String(key.clone()), bindings)
                    .map_err(|reason| format!("key {key:?}: {reason}"))?;
                parsed.insert(
                    key.clone(),
                    self.validate(value_type, entry, bindings)
                        .map_err(|reason| format!("{key}: {reason}"))?,
                );
            }
        }
        Ok(Value::Object(parsed))
    }

    /// JSON Schema projection of one node; cycles project to the permissive schema.
    fn project(
        &self,
        id: &TypeNodeId,
        bindings: &Bindings,
        seen: &mut Vec<TypeNodeId>,
    ) -> Result<Value, String> {
        if seen.contains(id) {
            return Ok(json!({}));
        }
        seen.push(id.clone());
        let projected = self.project_inner(id, bindings, seen);
        seen.pop();
        projected
    }

    #[allow(clippy::too_many_lines)]
    fn project_inner(
        &self,
        id: &TypeNodeId,
        bindings: &Bindings,
        seen: &mut Vec<TypeNodeId>,
    ) -> Result<Value, String> {
        let node = self.model.node(id)?;
        Ok(match &node.kind {
            TypeNodeKind::Keyword { name } => match name {
                KeywordTypeName::Any | KeywordTypeName::Unknown | KeywordTypeName::Object => {
                    json!({})
                }
                KeywordTypeName::Never
                | KeywordTypeName::Bigint
                | KeywordTypeName::Symbol
                | KeywordTypeName::Undefined
                | KeywordTypeName::Void => json!(false),
                KeywordTypeName::String => json!({"type": "string"}),
                KeywordTypeName::Number => json!({"type": "number"}),
                KeywordTypeName::Boolean => json!({"type": "boolean"}),
                KeywordTypeName::Other(other) => {
                    return Err(format!("keyword {other} has no Zod projection"));
                }
            },
            TypeNodeKind::Literal { value, .. } => match value {
                LiteralValue::Null => json!({"type": "null"}),
                LiteralValue::String(text) => json!({"const": text}),
                LiteralValue::Number(number) => json!({"const": number}),
                LiteralValue::Boolean(flag) => json!({"const": flag}),
                LiteralValue::BigInt { .. } => json!(false),
            },
            TypeNodeKind::Parenthesized { ty } => self.project(ty, bindings, seen)?,
            TypeNodeKind::Reference {
                name,
                target,
                arguments,
            } => self.project_reference(name, target, arguments, bindings, seen)?,
            TypeNodeKind::Union { types } => json!({
                "anyOf": types
                    .iter()
                    .map(|member| self.project(member, bindings, seen))
                    .collect::<Result<Vec<_>, _>>()?
            }),
            TypeNodeKind::Intersection { types } => json!({
                "allOf": types
                    .iter()
                    .map(|member| self.project(member, bindings, seen))
                    .collect::<Result<Vec<_>, _>>()?
            }),
            TypeNodeKind::Array { element } => {
                json!({"type": "array", "items": self.project(element, bindings, seen)?})
            }
            TypeNodeKind::Tuple { elements } => json!({
                "type": "array",
                "prefixItems": elements
                    .iter()
                    .filter(|element| !element.rest)
                    .map(|element| self.project(&element.ty, bindings, seen))
                    .collect::<Result<Vec<_>, _>>()?
            }),
            TypeNodeKind::Object { members } => self.project_object(members, bindings, seen)?,
            other => return Err(format!("{} has no Zod projection", kind_name(other))),
        })
    }

    fn project_reference(
        &self,
        name: &str,
        target: &TypeTargetModel,
        arguments: &[TypeNodeId],
        bindings: &Bindings,
        seen: &mut Vec<TypeNodeId>,
    ) -> Result<Value, String> {
        match target {
            TypeTargetModel::Declaration { symbol } => {
                let declaration = self.model.declaration(symbol)?;
                let mut bound = Bindings::default();
                for (index, parameter) in declaration.type_parameters.iter().enumerate() {
                    let (node, under) = match arguments.get(index) {
                        Some(argument) => (argument.clone(), bindings.clone()),
                        None => match &parameter.default {
                            Some(default) => (default.clone(), bound.clone()),
                            None => {
                                return Err(format!(
                                    "{name}: missing type argument {}",
                                    parameter.name
                                ));
                            }
                        },
                    };
                    bound
                        .0
                        .insert(parameter.id.clone(), (node, Box::new(under)));
                }
                match declaration.kind {
                    DeclarationKind::Enum => Err(format!(
                        "{}: enums have no Zod projection",
                        declaration.name
                    )),
                    DeclarationKind::Alias => {
                        let ty = declaration
                            .ty
                            .as_ref()
                            .ok_or_else(|| format!("{}: alias has no type", declaration.name))?;
                        self.project(ty, &bound, seen)
                    }
                    DeclarationKind::Interface | DeclarationKind::Class => {
                        let mut parts = declaration
                            .extends
                            .iter()
                            .map(|base| self.project(base, &bound, seen))
                            .collect::<Result<Vec<_>, _>>()?;
                        parts.push(self.project_object(&declaration.members, &bound, seen)?);
                        Ok(if parts.len() == 1 {
                            parts.remove(0)
                        } else {
                            json!({"allOf": parts})
                        })
                    }
                }
            }
            TypeTargetModel::TypeParameter { parameter } => {
                let (node, under) = bindings
                    .0
                    .get(parameter)
                    .ok_or_else(|| format!("{name}: unbound type parameter"))?;
                self.project(node, under, seen)
            }
            TypeTargetModel::Standard { name: standard } => match standard.as_str() {
                "Array" | "ReadonlyArray" => {
                    let element = arguments
                        .first()
                        .ok_or_else(|| format!("{name}: array has no element type"))?;
                    Ok(json!({"type": "array", "items": self.project(element, bindings, seen)?}))
                }
                "Record" => {
                    let item = arguments
                        .get(1)
                        .ok_or_else(|| format!("{name}: record needs key and value types"))?;
                    Ok(json!({
                        "type": "object",
                        "additionalProperties": self.project(item, bindings, seen)?
                    }))
                }
                "Date" => Ok(json!({"type": "string", "format": "date-time"})),
                other => Err(format!("standard type {other} has no Zod projection")),
            },
            TypeTargetModel::CrossFace { .. } | TypeTargetModel::External { .. } => {
                Err(format!("{name}: reference outside the artifact face"))
            }
        }
    }

    fn project_object(
        &self,
        members: &[MemberModel],
        bindings: &Bindings,
        seen: &mut Vec<TypeNodeId>,
    ) -> Result<Value, String> {
        let mut properties = Map::new();
        let mut required = Vec::new();
        let mut additional = None;
        let mut symbols = 0;
        for member in members {
            let MemberModel::Defined(member) = member else {
                return Err("unsupported model variant".to_owned());
            };
            let base = &member.base;
            if base.is_static || base.visibility != MemberVisibility::Public {
                continue;
            }
            if base.computed == Some(ComputedMember::Symbol) {
                symbols += 1;
                continue;
            }
            match &member.kind {
                MemberKind::Index { signature } => {
                    additional = Some(self.project(&signature.returns, bindings, seen)?);
                }
                MemberKind::Property { ty } => {
                    let key = base.json_name.clone().unwrap_or_else(|| base.name.clone());
                    if !base.optional {
                        required.push(key.clone());
                    }
                    properties.insert(key, self.project(ty, bindings, seen)?);
                }
                other => {
                    return Err(format!(
                        "{} member {} is not data-schema projectable",
                        other.as_str(),
                        base.name
                    ));
                }
            }
        }
        if properties.is_empty() && additional.is_none() && symbols > 0 {
            return Ok(json!({}));
        }
        let mut schema = json!({"type": "object", "properties": properties, "required": required});
        if let Some(additional) = additional {
            schema["additionalProperties"] = additional;
        }
        Ok(schema)
    }
}

impl TypertSchema for ModelSchema {
    fn parse(&self, value: TypertBoundaryValue) -> anyhow::Result<TypertBoundaryValue> {
        match value {
            TypertBoundaryValue::Undefined if self.accepts_undefined => {
                Ok(TypertBoundaryValue::Undefined)
            }
            TypertBoundaryValue::Undefined => Err(anyhow::anyhow!("required")),
            TypertBoundaryValue::Json(value) => self
                .validate(&self.root, &value, &Bindings::default())
                .map(TypertBoundaryValue::Json)
                .map_err(|reason| anyhow::anyhow!("{reason}")),
        }
    }

    fn to_json_schema(&self) -> anyhow::Result<Value> {
        self.project(&self.root, &Bindings::default(), &mut Vec::new())
            .map_err(|reason| anyhow::anyhow!("{reason}"))
    }
}

fn keyword(name: &KeywordTypeName, value: &Value) -> Result<Value, String> {
    let accepted = match name {
        KeywordTypeName::Any | KeywordTypeName::Unknown => true,
        KeywordTypeName::String => value.is_string(),
        KeywordTypeName::Number => value.is_number(),
        KeywordTypeName::Boolean => value.is_boolean(),
        KeywordTypeName::Object => value.is_object() || value.is_array(),
        KeywordTypeName::Never
        | KeywordTypeName::Bigint
        | KeywordTypeName::Symbol
        | KeywordTypeName::Undefined
        | KeywordTypeName::Void => false,
        KeywordTypeName::Other(other) => {
            return Err(format!("keyword {other} has no Zod projection"));
        }
    };
    if accepted {
        Ok(value.clone())
    } else {
        Err(format!("expected {}", name.as_str()))
    }
}

fn literal_matches(literal: &LiteralValue, value: &Value) -> bool {
    match literal {
        LiteralValue::String(text) => value.as_str() == Some(text),
        LiteralValue::Number(number) => value.as_number() == Some(number),
        LiteralValue::Boolean(flag) => value.as_bool() == Some(*flag),
        LiteralValue::Null => value.is_null(),
        LiteralValue::BigInt { .. } => false,
    }
}

fn literal_text(literal: &LiteralValue) -> String {
    match literal {
        LiteralValue::String(text) => format!("{text:?}"),
        LiteralValue::Number(number) => number.to_string(),
        LiteralValue::Boolean(flag) => flag.to_string(),
        LiteralValue::Null => "null".to_owned(),
        LiteralValue::BigInt { digits } => format!("{digits}n"),
    }
}

/// Zod's intersection merge: objects merge key-wise, arrays element-wise, other values must be
/// identical.
fn merge(left: Value, right: Value) -> Result<Value, String> {
    match (left, right) {
        (Value::Object(mut left), Value::Object(right)) => {
            for (key, value) in right {
                let merged = match left.remove(&key) {
                    Some(existing) => merge(existing, value)?,
                    None => value,
                };
                left.insert(key, merged);
            }
            Ok(Value::Object(left))
        }
        (Value::Array(left), Value::Array(right)) if left.len() == right.len() => left
            .into_iter()
            .zip(right)
            .map(|(left, right)| merge(left, right))
            .collect::<Result<Vec<_>, _>>()
            .map(Value::Array),
        (left, right) if left == right => Ok(left),
        _ => Err("intersection results could not be merged".to_owned()),
    }
}

fn kind_name(kind: &TypeNodeKind) -> &'static str {
    match kind {
        TypeNodeKind::Keyword { .. } => "keyword",
        TypeNodeKind::Literal { .. } => "literal",
        TypeNodeKind::Parenthesized { .. } => "parenthesized",
        TypeNodeKind::Reference { .. } => "reference",
        TypeNodeKind::Union { .. } => "union",
        TypeNodeKind::Intersection { .. } => "intersection",
        TypeNodeKind::Array { .. } => "array",
        TypeNodeKind::Tuple { .. } => "tuple",
        TypeNodeKind::Object { .. } => "object",
        TypeNodeKind::Function { .. } => "function",
        TypeNodeKind::Constructor { .. } => "constructor",
        TypeNodeKind::IndexedAccess { .. } => "indexed-access",
        TypeNodeKind::Operator { .. } => "operator",
        TypeNodeKind::Conditional { .. } => "conditional",
        TypeNodeKind::Infer { .. } => "infer",
        TypeNodeKind::Mapped { .. } => "mapped",
        TypeNodeKind::TemplateLiteral { .. } => "template-literal",
        TypeNodeKind::TypeQuery { .. } => "type-query",
        TypeNodeKind::ImportType { .. } => "import-type",
        TypeNodeKind::Predicate { .. } => "predicate",
        TypeNodeKind::This => "this",
    }
}
