//! Tool-result code units survive the real provider request serialization.

use seekdeep_llm::{CallId, ContentBlock, GenerateOptions, Message, MessageRole, MessageSource};
use seekdeep_llm_deepseek::serialize::{RequestDefaults, serialize_messages, serialize_request};

#[test]
fn provider_tool_text_remains_a_string_without_an_extra_escape_layer() {
    let message = Message::tool_result(
        &CallId::new("lossless-call"),
        vec![ContentBlock::text_utf16(&[0xd800])],
        false,
    );
    let wire = serialize_messages(&[message]).unwrap();
    assert_eq!(
        serde_json::to_string(&wire).unwrap(),
        r#"[{"role":"tool","tool_call_id":"lossless-call","content":"\ud800"}]"#,
    );
}

#[test]
fn every_message_role_and_mixed_tool_result_retains_text_code_units() {
    let messages = [
        Message::new(
            MessageRole::System,
            vec![ContentBlock::text_utf16(&[0xdfff])],
            MessageSource::plugin("fixture"),
        ),
        Message::user(
            vec![
                ContentBlock::text_utf16(&[0xd800]),
                ContentBlock::text("\\ud800"),
            ],
            MessageSource::user(),
        ),
        Message::assistant(
            vec![
                ContentBlock::text_utf16(&[0xd83d]),
                ContentBlock::text_utf16(&[0xde00]),
            ],
            "deepseek",
            "fixture",
        ),
        Message::user(
            vec![
                ContentBlock::text("context"),
                ContentBlock::ToolResult {
                    tool_call_id: CallId::new("nested"),
                    content: vec![ContentBlock::text_utf16(&[0xdfff])],
                    is_error: Some(false),
                },
            ],
            MessageSource::user(),
        ),
    ];
    assert_eq!(
        serde_json::to_string(&serialize_messages(&messages).unwrap()).unwrap(),
        r#"[{"role":"system","content":"\udfff"},{"role":"user","content":"\ud800\\ud800"},{"role":"assistant","content":"😀"},{"role":"user","content":"context"},{"role":"tool","tool_call_id":"nested","content":"\udfff"}]"#,
    );
}

#[test]
fn complete_provider_request_bytes_preserve_lone_surrogate_tool_results() {
    let options = GenerateOptions::new(
        "deepseek".into(),
        "fixture".into(),
        vec![Message::tool_result(
            &CallId::new("lossless-call"),
            vec![ContentBlock::text_utf16(&[0xd800])],
            false,
        )],
    );
    let wire = serialize_request(&options, RequestDefaults::default()).unwrap();
    let bytes = serde_json::to_vec(&wire).unwrap();
    assert_eq!(
        String::from_utf8(bytes).unwrap(),
        r#"{"model":"fixture","messages":[{"role":"tool","tool_call_id":"lossless-call","content":"\ud800"}],"stream":true,"stream_options":{"include_usage":true}}"#,
    );
}

#[test]
#[ignore = "requires SEEKDEEP_LLM_TEXT_SOURCE generated by the mounted pinned TypeScript oracle"]
fn mounted_source_tool_text_matches_message_and_provider_request_bytes() {
    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct SourceFixture {
        fixture_content: Vec<ContentBlock>,
        message: Message,
        message_json: String,
        wire_json: String,
        request_json: String,
    }

    let path = std::env::var("SEEKDEEP_LLM_TEXT_SOURCE").expect("source fixture path");
    let raw = std::fs::read_to_string(path).expect("mounted source output");
    let source: SourceFixture = serde_json::from_str(&raw).expect("source output schema");
    let constructed =
        Message::tool_result(&CallId::new("lossless-call"), source.fixture_content, false);
    assert_eq!(constructed.content(), source.message.content());
    assert_eq!(constructed.source(), source.message.source());
    assert_eq!(
        serde_json::to_string(&source.message).unwrap(),
        source.message_json
    );
    let options = GenerateOptions::new("deepseek".into(), "fixture".into(), vec![source.message]);
    assert_eq!(
        serde_json::to_string(&serialize_messages(&options.messages).unwrap()).unwrap(),
        source.wire_json,
    );
    assert_eq!(
        serde_json::to_string(&serialize_request(&options, RequestDefaults::default()).unwrap())
            .unwrap(),
        source.request_json,
    );
}
