[package]
name = "seekdeep-agent-presets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
indexmap.workspace = true
path-clean.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yml.workspace = true
seekdeep-core = { path = "../core" }
seekdeep-loader = { path = "../loader" }
seekdeep-util = { path = "../util" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
