//! Run the pinned bundled-runtime launch suite against generated Rust-backed carriers.

use std::{
    ffi::OsString,
    path::{Path, PathBuf},
    process::Command,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let arguments = std::env::args_os().skip(1).collect::<Vec<_>>();
    let source = match arguments.as_slice() {
        [source] | [source, _] => Path::new(source).canonicalize()?,
        _ => {
            return Err(
                "usage: bundled_runtime_source_parity <pinned-source> [test-python]".into(),
            );
        }
    };
    verify_pin(&source)?;
    let repository = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let sdk = repository.join("python/sdk/src");
    let runtime = repository.join("python/sdk-runtime/src");
    require_generated(&sdk.join("deepseek_harness/__init__.py"))?;
    require_generated(&runtime.join("deepseek_harness_runtime/__init__.py"))?;
    require_generated(
        &runtime.join(
            "deepseek_harness_runtime/runtime/node/node_modules/@seekdeep-ai/seekdeep-sdk-jsonrpc-demo/lib/packaged-bin.js",
        ),
    )?;

    let temporary = tempfile::tempdir()?;
    let test = temporary
        .path()
        .join("python/sdk/tests/test_bundled_runtime.py");
    std::fs::create_dir_all(test.parent().ok_or("test parent absent")?)?;
    std::fs::write(
        &test,
        port_text(&std::fs::read_to_string(
            source.join("python/sdk/tests/test_bundled_runtime.py"),
        )?),
    )?;
    let minimal = temporary
        .path()
        .join("examples/jsonrpc-agent/minimal.cordis.yml");
    std::fs::create_dir_all(minimal.parent().ok_or("minimal config parent absent")?)?;
    std::fs::write(
        minimal,
        port_text(&std::fs::read_to_string(
            source.join("examples/jsonrpc-agent/minimal.cordis.yml"),
        )?),
    )?;

    let python = arguments
        .get(1)
        .map_or_else(|| source.join("python/sdk/.venv/bin/python"), PathBuf::from);
    if !python.is_absolute() || !python.is_file() {
        return Err("test Python must be an absolute executable path".into());
    }
    let python_path: OsString = std::env::join_paths([sdk, runtime])?;
    let status = Command::new(python)
        .args([
            "-m",
            "pytest",
            "-p",
            "no:cacheprovider",
            "-o",
            "addopts=",
            "-q",
        ])
        .arg(test)
        .current_dir(temporary.path())
        .env("PYTHONPATH", python_path)
        .env("PYTHONNOUSERSITE", "1")
        .env("PYTHONDONTWRITEBYTECODE", "1")
        .env_remove("SEEKDEEP_RUNTIME_MODE")
        .env_remove("SEEKDEEP_CORDIS_CONFIG")
        .status()?;
    if !status.success() {
        return Err("pinned bundled-runtime suite failed against generated carriers".into());
    }
    println!("pinned bundled-runtime suite passed against native exe and development carrier");
    Ok(())
}

fn require_generated(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string(path)?;
    if !text.starts_with("# Generated by seekdeep-python-sdk;")
        && !text.starts_with("// Generated launch binding;")
    {
        return Err(format!("generated carrier is absent or unowned: {}", path.display()).into());
    }
    Ok(())
}

fn port_text(source: &str) -> String {
    source
        .replace("@deepseek-ai/", "@seekdeep-ai/")
        .replace("dsh-", "seekdeep-")
        .replace("DSH_", "SEEKDEEP_")
        .replace("DeepSeek Harness", "SeekDeep Harness")
        .replace("deepseek-harness", "seekdeep-harness")
}

fn verify_pin(source: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let output = Command::new("git")
        .arg("-C")
        .arg(source)
        .args(["rev-parse", "HEAD"])
        .output()?;
    let pin = include_str!("../../../SOURCE_SNAPSHOT")
        .lines()
        .find_map(|line| line.strip_prefix("commit="))
        .ok_or("source pin absent")?;
    if !output.status.success() || String::from_utf8_lossy(&output.stdout).trim() != pin {
        return Err("oracle differs from SOURCE_SNAPSHOT".into());
    }
    Ok(())
}
