//! Marker-delimited subsystem regions and the inherited Cordis page.

use std::sync::LazyLock;

use indexmap::IndexMap;
use regex::Regex;

use super::{CordisCatalogPolicy, EventEntry, ServiceEntry, ServiceMemberKind};
use crate::{
    Result,
    text::{locale_compare, utf16_compare},
};

/// Opening delimiter; the containing page owns every byte outside the region.
pub const REGION_BEGIN: &str =
    "<!-- BEGIN GENERATED cordis-surface (gen-cordis-catalog.ts) — do not edit between markers -->";
/// Closing delimiter of a generated Cordis region.
pub const REGION_END: &str = "<!-- END GENERATED cordis-surface -->";

const FENCE: &str = "```ts cordis-catalog";
const NOTICE: &str = "Generated from source by `scripts/gen-cordis-catalog.ts` (verified fresh by `pnpm run verify-cordis-catalog` in doc-sync; regenerate with `pnpm run gen-cordis-catalog`) — this section is byte-identical in both language sides of the page. Signature blocks use a `ts cordis-catalog` fence and keep the original source JSDoc; dispatch modes are defined in the [primer](../cordis-primer.md#dispatch-modes), and the framework-inherited `ctx` API lives in [cordis-api/inherited.md](../cordis-api/inherited.md).";
const GATE_NOTICE: &str = "This file is GENERATED from source (`scripts/gen-cordis-catalog.ts`) and verified fresh by `pnpm run verify-cordis-catalog` (part of `doc-sync`) — do not edit it by hand. Signature blocks use a `ts cordis-catalog` fence and include the original source JSDoc immediately before each event or service method. doc-typecheck skips these bare declaration fragments; type names in a signature link to the page that documents them.";

/// Renders supplied services, then grouped and sorted events, including both markers.
///
/// A linked type owned by `page` is omitted from that page's cross-links.
/// Service input order is retained; properties appear only in the runtime catalog.
///
/// # Errors
/// Rejects an invalid caller-owned type-name regular expression.
pub fn render_page_region(
    page: &str,
    services: &[ServiceEntry],
    events: &[EventEntry],
    policy: &CordisCatalogPolicy,
) -> Result<String> {
    let mut lines = vec![
        REGION_BEGIN.to_owned(),
        String::new(),
        "<a id=\"cordis-surface\"></a>".to_owned(),
        String::new(),
        "## Cordis API".to_owned(),
        String::new(),
        NOTICE.to_owned(),
        String::new(),
    ];
    for service in services {
        render_service(service, page, &policy.linked_type_pages, &mut lines)?;
    }
    let mut scopes = events
        .iter()
        .map(|event| event.scope.as_str())
        .collect::<Vec<_>>();
    scopes.sort_by(|left, right| utf16_compare(left, right));
    scopes.dedup();
    for scope in scopes {
        anchor(&format!("{scope}/* events"), &mut lines);
        lines.extend([format!("### `{scope}/*` events"), String::new()]);
        let mut selected = events
            .iter()
            .filter(|event| event.scope == scope)
            .collect::<Vec<_>>();
        selected.sort_by(|left, right| locale_compare(&left.name, &right.name));
        for event in selected {
            render_event(event, page, &policy.linked_type_pages, &mut lines)?;
        }
    }
    while lines.last().is_some_and(String::is_empty) {
        lines.pop();
    }
    lines.push(REGION_END.to_owned());
    Ok(lines.join("\n"))
}

/// Renders the inherited framework page in caller-curated order.
pub fn render_inherited_page(policy: &CordisCatalogPolicy) -> String {
    let mut lines = vec![
        "<!-- Generated by scripts/gen-cordis-catalog.ts — do not edit by hand.".to_owned(),
        "     Run `pnpm run gen-cordis-catalog` to regenerate. -->".to_owned(),
        String::new(), "# Inherited Cordis API".to_owned(), String::new(),
        "The framework `ctx` members and events every plugin sees beyond the harness tier — pinned vendor source ([vendoring policy](../../vendor/README.md)), summarized tersely so the harness pages stay focused on repository-owned vocabulary. Detailed Context, Fiber, Registry, and Service APIs are generated in [context.md](context.md), [fiber.md](fiber.md), [registry.md](registry.md), and [service.md](service.md); the event-dispatch methods in [events.md](events.md).".to_owned(),
        String::new(), GATE_NOTICE.to_owned(), String::new(),
        "## Inherited `ctx` members (cordis core + loader/hmr/timer)".to_owned(), String::new(),
    ];
    for service in &policy.inherited_services {
        lines.push(format!(
            "- `{}` — {} ([`{}`](../../{}))",
            service.name,
            service.summary,
            service.source,
            source_file(&service.source)
        ));
    }
    lines.extend([
        String::new(),
        "## Inherited events (cordis core + loader/hmr/timer)".to_owned(),
        String::new(),
    ]);
    for event in &policy.inherited_events {
        lines.push(format!(
            "- `{}` — {} ([`{}`](../../{}))",
            event.name,
            event.summary,
            event.source,
            source_file(&event.source)
        ));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn render_event(
    event: &EventEntry,
    page: &str,
    linked: &IndexMap<String, String>,
    lines: &mut Vec<String>,
) -> Result<()> {
    anchor(&format!("{} — {}", event.name, event.mode.as_str()), lines);
    lines.extend([
        format!("#### `{}` — {}", event.name, event.mode.as_str()),
        String::new(),
    ]);
    if !event.doc.is_empty() {
        lines.extend([event.doc.clone(), String::new()]);
    }
    lines.extend([
        FENCE.to_owned(),
        event.js_doc.clone(),
        event.signature.clone(),
        "```".to_owned(),
        String::new(),
    ]);
    if let Some(links) = type_links(&event.signature, page, linked)? {
        lines.extend([links, String::new()]);
    }
    lines.extend([
        format!(
            "Source: [`{}`](../../{})",
            event.source,
            source_file(&event.source)
        ),
        String::new(),
    ]);
    Ok(())
}

fn render_service(
    service: &ServiceEntry,
    page: &str,
    linked: &IndexMap<String, String>,
    lines: &mut Vec<String>,
) -> Result<()> {
    let kind = if service.is_abstract {
        " (abstract seam)"
    } else {
        ""
    };
    anchor(
        &format!("ctx.{} — {}{kind}", service.key, service.type_name),
        lines,
    );
    lines.extend([
        format!("### `ctx.{}` — `{}`{kind}", service.key, service.type_name),
        String::new(),
    ]);
    if !service.doc.is_empty() {
        lines.extend([service.doc.clone(), String::new()]);
    }
    let methods = service
        .methods
        .iter()
        .filter(|member| member.kind != Some(ServiceMemberKind::Property))
        .collect::<Vec<_>>();
    if !methods.is_empty() {
        lines.push(FENCE.to_owned());
        for (index, method) in methods.iter().enumerate() {
            if index > 0 {
                lines.push(String::new());
            }
            lines.extend([method.js_doc.clone(), method.signature.clone()]);
        }
        lines.extend(["```".to_owned(), String::new()]);
        let signature = methods
            .iter()
            .map(|method| method.signature.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        if let Some(links) = type_links(&signature, page, linked)? {
            lines.extend([links, String::new()]);
        }
    }
    lines.extend([
        format!(
            "Source: [`{}`](../../{})",
            service.source,
            source_file(&service.source)
        ),
        String::new(),
    ]);
    Ok(())
}

fn type_links(
    signature: &str,
    page: &str,
    linked: &IndexMap<String, String>,
) -> Result<Option<String>> {
    let mut names = Vec::new();
    for name in linked.keys() {
        let pattern = super::type_pattern(name)?;
        if pattern.is_match(signature) {
            names.push(name);
        }
    }
    names.sort_by(|left, right| utf16_compare(left, right));
    let links = names
        .into_iter()
        .filter(|name| linked[*name] != page)
        .map(|name| format!("[{name}]({})", linked[name]))
        .collect::<Vec<_>>();
    Ok((!links.is_empty()).then(|| format!("Types: {}", links.join(" · "))))
}

fn anchor(heading: &str, lines: &mut Vec<String>) {
    static NON_SLUG: LazyLock<Regex> =
        LazyLock::new(|| Regex::new(r"[^\p{L}\p{N} -]").expect("GitHub heading characters"));
    let lowercase = heading.to_lowercase();
    let slug = NON_SLUG.replace_all(&lowercase, "").replace(' ', "-");
    lines.extend([format!("<a id=\"{slug}\"></a>"), String::new()]);
}

fn source_file(pointer: &str) -> &str {
    pointer.split(':').next().unwrap_or_default()
}
