//! Deterministic Markdown/Mermaid workspace module graph generation.

use std::{
    collections::{HashMap, HashSet},
    path::Path,
};

use crate::package_graph::{
    PackageGraphNode, collect_package_graph, escape_mermaid_label, graph_node_id,
};

/// Generated module graph artifact path.
pub const MODULE_GRAPH_OUTPUT: &str = "docs/module-graph.md";
/// Source-defined package-group order.
pub const MODULE_GRAPH_GROUP_ORDER: &[&str] = &[
    "util",
    "llm",
    "core",
    "goal",
    "bash",
    "fs",
    "skill",
    "compact",
    "subagent",
    "web",
    "spill",
    "timeout",
    "todo",
    "plan",
    "cordis",
    "hooks",
    "session-persistence",
    "session-query",
    "session-title",
    "support",
    "acp",
    "ui",
];

/// Renders a complete target module-graph document.
#[must_use]
pub fn render_module_graph(packages: &[PackageGraphNode]) -> String {
    let mut edges = Vec::new();
    for package in packages {
        for dependency in &package.dependencies {
            edges.push(format!(
                "  {} --> {}",
                graph_node_id("pkg", &package.short),
                graph_node_id("pkg", dependency)
            ));
        }
    }
    let by_short = packages
        .iter()
        .map(|package| (package.short.as_str(), package))
        .collect::<HashMap<_, _>>();
    let mut seen = HashSet::new();
    let mut groups = packages
        .iter()
        .filter_map(|package| {
            seen.insert(package.group.as_str())
                .then_some(package.group.clone())
        })
        .collect::<Vec<_>>();
    groups.sort_by(|left, right| compare_group(left, right));
    let mut group_blocks = Vec::new();
    for group in groups {
        group_blocks.push(format!(
            "  subgraph {}[\"packages/{}\"]",
            graph_node_id("group", &group),
            escape_mermaid_label(&group)
        ));
        let mut members = packages
            .iter()
            .filter(|package| package.group == group)
            .collect::<Vec<_>>();
        members.sort_by(|left, right| left.short.encode_utf16().cmp(right.short.encode_utf16()));
        for package in members {
            group_blocks.push(format!(
                "    {}[\"{}\"]",
                graph_node_id("pkg", &package.short),
                escape_mermaid_label(&package.short)
            ));
        }
        group_blocks.push("  end".to_owned());
    }
    let rows = packages.iter().map(|package| {
        let dependencies = if package.dependencies.is_empty() {
            "—".to_owned()
        } else {
            package
                .dependencies
                .iter()
                .map(|dependency| {
                    by_short.get(dependency.as_str()).map_or_else(
                        || format!("`{dependency}`"),
                        |dependency| package_link(dependency),
                    )
                })
                .collect::<Vec<_>>()
                .join(", ")
        };
        format!(
            "| {} | `{}` | {dependencies} |",
            package_link(package),
            package.group
        )
    });
    let mut lines = vec![
        "<!-- Generated by the Rust module-graph generator — do not edit by hand.".to_owned(),
        "     Run `pnpm run gen-module-graph` to regenerate. -->".to_owned(),
        String::new(),
        "# Module dependency graph".to_owned(),
        String::new(),
        "Inter-package dependencies among the `@seekdeep-ai/seekdeep-*` harness packages, derived from each package's `peerDependencies` (the canonical runtime-dependency signal) and grouped by the `packages/<group>/<pkg>` hierarchy. An edge `a --> b` means package `a` depends on package `b`. Names have the `@seekdeep-ai/seekdeep-` prefix stripped.".to_owned(),
        String::new(),
        "```mermaid".to_owned(),
        "flowchart TD".to_owned(),
    ];
    lines.extend(group_blocks);
    lines.extend(edges);
    lines.extend([
        "```".to_owned(),
        String::new(),
        "| Package | Group | Depends on |".to_owned(),
        "| --- | --- | --- |".to_owned(),
    ]);
    lines.extend(rows);
    lines.push(String::new());
    lines.join("\n")
}

/// Generates the live graph from compatibility manifests.
///
/// # Errors
///
/// Returns package discovery, manifest, or graph-cycle failures.
pub fn generate_module_graph(root: &Path) -> anyhow::Result<String> {
    let groups = MODULE_GRAPH_GROUP_ORDER
        .iter()
        .map(|group| (*group).to_owned())
        .collect::<Vec<_>>();
    Ok(render_module_graph(&collect_package_graph(
        root,
        &groups,
        "gen-module-graph",
    )?))
}

fn package_link(package: &PackageGraphNode) -> String {
    format!("[`{}`](../{})", package.short, package.relative)
}

fn compare_group(left: &str, right: &str) -> std::cmp::Ordering {
    MODULE_GRAPH_GROUP_ORDER
        .iter()
        .position(|group| *group == left)
        .unwrap_or(usize::MAX)
        .cmp(
            &MODULE_GRAPH_GROUP_ORDER
                .iter()
                .position(|group| *group == right)
                .unwrap_or(usize::MAX),
        )
        .then_with(|| left.encode_utf16().cmp(right.encode_utf16()))
}
