//! Generated Rust scope-filtered event requirement catalog.

use std::fmt::Write as _;

/// Fixed target path for the generated catalog.
pub const OUTPUT_PATH: &str = "crates/scope/src/scoped_events.rs";

/// Scoped events whose Rust `EventArgs` carry an external routing subject.
pub const SUBJECT_EVENTS: &[&str] = &[
    "agent/created",
    "agent/disposed",
    "agent/error",
    "agent/inbox/claimed",
    "agent/inbox/discarded",
    "agent/inbox/inserted",
    "agent/pre-step",
    "agent/request",
    "agent/request-error",
    "agent/session-start",
    "agent/status",
    "agent/turn-stopping",
    "approval/request",
    "goal/changed",
    "system-prompt/assemble",
    "tools/code-dispatch-log",
    "tools/execute",
    "tools/post-execute",
    "tools/pre-execute",
    "tools/result",
];

/// Scoped events requiring a carrier whose payload intentionally omits its key.
pub const PRESENCE_EVENTS: &[&str] = &[
    "session/created",
    "session/disposed",
    "session/event",
    "session/flush",
    "subagent/end",
    "subagent/start",
];

/// Renders the complete generated runtime module.
#[must_use]
pub fn render_scoped_events() -> String {
    let mut output = String::new();
    output.push_str(
        r"//! Generated scope-filtered event subject requirements.
//!
//! @generated by `pnpm run gen-scoped-events`; do not edit by hand.

/// How a scope-filtered event exposes its routing subject.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ScopedSubjectRequirement {
    /// A carrier is required, but the payload has no external subject.
    Presence,
    /// The payload-derived subject must equal the carrier key.
    Subject,
}

/// Returns the generated requirement for one event, or `None` when unscoped.
#[must_use]
pub fn scoped_subject_requirement(event: &str) -> Option<ScopedSubjectRequirement> {
    use ScopedSubjectRequirement::{Presence, Subject};

    Some(match event {
",
    );
    render_match_arm(&mut output, SUBJECT_EVENTS, "Subject");
    render_match_arm(&mut output, PRESENCE_EVENTS, "Presence");
    output.push_str(
        r"        _ => return None,
    })
}
",
    );
    output
}

fn render_match_arm(output: &mut String, events: &[&str], requirement: &str) {
    if requirement == "Presence" {
        let first = events[..4]
            .iter()
            .map(|event| format!("{event:?}"))
            .collect::<Vec<_>>()
            .join(" | ");
        let second = events[4..]
            .iter()
            .map(|event| format!("{event:?}"))
            .collect::<Vec<_>>()
            .join(" | ");
        let _ = writeln!(output, "        {first}");
        let _ = writeln!(output, "        | {second} => {requirement},");
        return;
    }
    for (index, event) in events.iter().enumerate() {
        if index + 1 == events.len() {
            let _ = writeln!(output, "        | {event:?} => {requirement},");
        } else if index == 0 {
            let _ = writeln!(output, "        {event:?}");
        } else {
            let _ = writeln!(output, "        | {event:?}");
        }
    }
}

/// Generates or verifies the fixed scoped-event catalog.
///
/// # Errors
///
/// Returns repository read/write failures or a stale-artifact diagnostic.
pub fn run_scoped_events_generator(root: &std::path::Path, check: bool) -> anyhow::Result<String> {
    let content = render_scoped_events();
    let output = root.join(OUTPUT_PATH);
    if check {
        let committed = std::fs::read_to_string(&output).ok();
        anyhow::ensure!(
            committed.as_deref() == Some(&content),
            "gen-scoped-events: {OUTPUT_PATH} is stale. Run `pnpm run gen-scoped-events` and commit it."
        );
        return Ok(format!("gen-scoped-events: {OUTPUT_PATH} is up to date.\n"));
    }
    std::fs::write(output, content)?;
    Ok(format!("gen-scoped-events: wrote {OUTPUT_PATH}.\n"))
}
