[package]
name = "seekdeep-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
seekdeep-cordis = { path = "../cordis" }
seekdeep-invariants = { path = "../invariants" }
seekdeep-llm = { path = "../llm" }
seekdeep-sandbox = { path = "../sandbox" }
seekdeep-util = { path = "../util" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
