//! Python type declarations and direct calls into the native SDK implementation.

use std::collections::BTreeMap;

pub(super) fn sources() -> crate::Result<BTreeMap<String, String>> {
    let encode = |value: serde_json::Value| {
        serde_json::to_string(&value.to_string())
            .map_err(|error| crate::Error::new(crate::ErrorKind::Value, error.to_string()))
    };
    let client = CLIENT.replace(
        "__DEFAULTS__",
        &encode(serde_json::json!(crate::HarnessConfig::default()))?,
    );
    let api = API.replace(
        "__DEFAULTS__",
        &encode(serde_json::json!(crate::HarnessOptions::default()))?,
    );
    Ok(BTreeMap::from([
        ("__init__.py".to_owned(), INIT.to_owned()),
        ("models.py".to_owned(), MODELS.to_owned()),
        ("errors.py".to_owned(), ERRORS.to_owned()),
        ("client.py".to_owned(), client),
        ("api.py".to_owned(), api),
    ]))
}

const INIT: &str = r#"# Generated by seekdeep-python-sdk; behavior is compiled Rust.
from .api import DeepSeekHarness, DeepSeekHarnessConfig, RunResult, Session
from .client import HarnessClient, HarnessConfig
from .errors import SdkProtocolError
from .models import IncomingRequest, InitializeResponse, JsonObject, Notification, ServerInfo

__all__ = [
    "DeepSeekHarness", "DeepSeekHarnessConfig", "Session", "RunResult",
    "HarnessClient", "HarnessConfig", "SdkProtocolError", "IncomingRequest",
    "InitializeResponse", "JsonObject", "Notification", "ServerInfo",
]
"#;

const MODELS: &str = r#"# Generated by seekdeep-python-sdk; foreign API type declarations.
from __future__ import annotations
from dataclasses import dataclass
from typing import TypeAlias
from pydantic import BaseModel

JsonScalar: TypeAlias = str | int | float | bool | None
JsonValue: TypeAlias = JsonScalar | dict[str, "JsonValue"] | list["JsonValue"]
JsonObject: TypeAlias = dict[str, JsonValue]

@dataclass(slots=True)
class Notification:
    method: str
    payload: JsonObject

@dataclass(slots=True)
class IncomingRequest:
    id: str | int
    method: str
    payload: JsonObject

class ServerInfo(BaseModel):
    name: str | None = None
    version: str | None = None

class InitializeResponse(BaseModel):
    serverInfo: ServerInfo | None = None
"#;

const ERRORS: &str = r#"# Generated by seekdeep-python-sdk; foreign exception declarations.
from __future__ import annotations

class HarnessError(Exception):
    """Base exception for SDK and runtime failures."""

class TransportClosedError(HarnessError):
    """The runtime subprocess exited or closed its transport."""

class SdkProtocolError(HarnessError):
    """The runtime returned data outside the SDK protocol."""

class JsonRpcError(HarnessError):
    """A JSON-RPC error response."""
    def __init__(self, code: int | None, message: str, data: object | None = None) -> None:
        super().__init__(message)
        self.code, self.message, self.data = code, message, data
"#;

const CLIENT: &str = r#"# Generated by seekdeep-python-sdk; client behavior is compiled Rust.
from __future__ import annotations
import json
import os
import weakref
from dataclasses import asdict, dataclass
from typing import Callable, TypeAlias, TypeVar
from pydantic import BaseModel
from deepseek_harness_runtime._bridge import Context, invoke
from .models import IncomingRequest, InitializeResponse, JsonObject, JsonValue, Notification

ModelT = TypeVar("ModelT", bound=BaseModel)
NotificationFilter: TypeAlias = Callable[[Notification], bool]
_DEFAULTS = json.loads(__DEFAULTS__)

@dataclass(slots=True)
class HarnessConfig:
    runtime_bin: str | None = _DEFAULTS["runtime_bin"]
    bridge_bin: str | None = _DEFAULTS["bridge_bin"]
    launch_args_override: tuple[str, ...] | None = _DEFAULTS["launch_args_override"]
    cwd: str | None = _DEFAULTS["cwd"]
    env: dict[str, str] | None = _DEFAULTS["env"]
    request_timeout_seconds: float | None = _DEFAULTS["request_timeout_seconds"]
    shutdown_timeout_seconds: float | None = _DEFAULTS["shutdown_timeout_seconds"]

def _release(handle):
    try:
        invoke({"op":"handle.drop","handle":handle})
    except BaseException:
        pass

def _runtime_launch():
    try:
        from deepseek_harness_runtime import resolve_bundled_launch_args
    except ImportError as error:
        raise FileNotFoundError(
            "Unable to locate the bundled SeekDeep Harness SDK runtime. "
            "Install seekdeep-harness-runtime-bin or set HarnessConfig.runtime_bin."
        ) from error
    return resolve_bundled_launch_args()

def _runtime_config():
    from deepseek_harness_runtime import bundled_default_config_path
    return str(bundled_default_config_path())

class _Process:
    def __init__(self, value):
        self._handle, self.pid = value["handle"], value["pid"]
        self._finalizer = weakref.finalize(self, _release, self._handle)
    def poll(self):
        return invoke({"op":"process.poll","handle":self._handle})
    def wait(self, timeout=None):
        return invoke({"op":"process.wait","handle":self._handle,"timeout":timeout})
    def terminate(self):
        return invoke({"op":"process.terminate","handle":self._handle})
    def kill(self):
        return invoke({"op":"process.kill","handle":self._handle})

class _NotificationQueue:
    def __init__(self, client):
        self._client = client
    def qsize(self):
        return self._client._invoke("client.notification_count")
    def get_nowait(self):
        return self._client._invoke("client.next_notification", nonblocking=True)
    def get(self):
        return self._client.next_notification()

class HarnessClient:
    """Synchronous JSON-RPC client owned by the Rust implementation."""
    def __init__(self, config: HarnessConfig | None = None) -> None:
        self.config = config or HarnessConfig()
        self._prepare_context()
        self._handle = invoke({"op":"client.new","config":asdict(self.config),
            "owner":self._context.identity,"seed":list(os.urandom(16))},context=self._context)
        self._finalizer = weakref.finalize(self, _release, self._handle)

    def _prepare_context(self):
        self._context = Context({
            "runtime.launch":_runtime_launch,
            "runtime.config":_runtime_config,
            "notification.create":Notification,
            "config.read":lambda:json.dumps(asdict(self.config),separators=(",",":")),
        })
        self._notifications = _NotificationQueue(self)

    @classmethod
    def _from_native(cls, handle, config):
        self = cls.__new__(cls)
        config["launch_args_override"] = None if config["launch_args_override"] is None else tuple(config["launch_args_override"])
        self.config = HarnessConfig(**config)
        self._prepare_context()
        self._handle = handle
        self._finalizer = weakref.finalize(self, _release, handle)
        self._invoke("client.bind",owner=self._context.identity)
        return self

    def _invoke(self, operation, **arguments):
        return invoke({"op":operation,"handle":self._handle,**arguments},context=self._context)

    def _reference(self, value):
        return None if value is None else self._context.handle(value)

    @property
    def _proc(self):
        value = self._invoke("client.process")
        return None if value is None else _Process(value)

    def __enter__(self) -> "HarnessClient":
        self.start()
        return self
    def __exit__(self, _exc_type, _exc, _tb) -> None:
        self.close()
    def start(self) -> None:
        self._invoke("client.start")
    def close(self) -> None:
        self._invoke("client.close")
    def initialize(self, *, cwd: str, provider: str, model: str, max_tokens: int | None = None) -> InitializeResponse:
        return self._invoke("client.initialize",cwd=cwd,provider=provider,model=model,
            max_tokens=max_tokens,validator=self._reference(InitializeResponse))
    def session_prompt(self, session_id: str, content_blocks: list[JsonObject], *,
            on_notification: Callable[[Notification], None] | None = None,
            notification_subscription: "NotificationSubscription | None" = None) -> str:
        return self._invoke("client.prompt",session=session_id,content=content_blocks,
            observer=self._reference(on_notification),validator=self._reference(_SessionPromptResponse),
            subscription=None if notification_subscription is None else notification_subscription._handle)
    def request(self, method: str, params: JsonObject | None, *, response_model: type[ModelT],
            timeout_seconds: float | None = None,
            on_notification: Callable[[Notification], None] | None = None,
            notification_filter: NotificationFilter | None = None,
            notification_subscription: "NotificationSubscription | None" = None) -> ModelT:
        return self._invoke("client.request",method=method,params=params,validator=self._reference(response_model),
            timeout=timeout_seconds,observer=self._reference(on_notification),predicate=self._reference(notification_filter),
            subscription=None if notification_subscription is None else notification_subscription._handle)
    def _request_raw(self, method: str, params: JsonObject | None = None, *,
            timeout_seconds: float | None = None,
            on_notification: Callable[[Notification], None] | None = None,
            notification_filter: NotificationFilter | None = None,
            notification_subscription: "NotificationSubscription | None" = None) -> JsonValue:
        return self._invoke("client.request",method=method,params=params,validator=None,
            timeout=timeout_seconds,observer=self._reference(on_notification),predicate=self._reference(notification_filter),
            subscription=None if notification_subscription is None else notification_subscription._handle)
    def notify(self, method: str, params: JsonObject | None = None) -> None:
        self._invoke("client.notify",method=method,params=params)
    def next_notification(self) -> Notification:
        return self._invoke("client.next_notification")
    def next_request(self) -> IncomingRequest:
        return IncomingRequest(**self._invoke("client.next_request"))
    def respond(self, request_id: str | int, result: JsonValue) -> None:
        self._invoke("client.respond",id=request_id,result=result)
    def respond_error(self, request_id: str | int, *, code: int, message: str, data: JsonValue | None = None) -> None:
        self._invoke("client.respond_error",id=request_id,code=code,message=message,data=data)
    def subscribe_notifications(self, notification_filter: NotificationFilter | None = None) -> "NotificationSubscription":
        handle = self._invoke("client.subscribe",predicate=self._reference(notification_filter),session=None)
        return NotificationSubscription(self,handle)
    def subscribe_session_notifications(self, session_id: str) -> "NotificationSubscription":
        handle = self._invoke("client.subscribe",predicate=None,session=session_id)
        return NotificationSubscription(self,handle)
    def _handle_message(self, message: object) -> None:
        self._invoke("client.handle_message",message=message,original=self._reference(message))
    def _runtime_diagnostics(self) -> str:
        return self._invoke("client.diagnostics")

class NotificationSubscription:
    def __init__(self, client, handle):
        self._client, self._handle, self._closed = client, handle, False
        self._finalizer = weakref.finalize(self, _release, handle)
    def __enter__(self) -> "NotificationSubscription":
        return self
    def __exit__(self, _exc_type, _exc, _tb) -> None:
        self.close()
    def close(self) -> None:
        invoke({"op":"subscription.close","handle":self._handle},context=self._client._context)
        self._closed = True
    def next(self) -> Notification:
        return invoke({"op":"subscription.next","handle":self._handle},context=self._client._context)
    def drain(self, on_notification: Callable[[Notification], None]) -> None:
        invoke({"op":"subscription.drain","handle":self._handle,
            "observer":self._client._reference(on_notification)},context=self._client._context)

class _SessionPromptResponse(BaseModel):
    messageId: str
class _ShutdownResponse(BaseModel):
    pass

def _int_or_none(value: object) -> int | None:
    context = Context({})
    return invoke({"op":"api.int_or_none","value":context.handle(value)},context=context)
"#;

const API: &str = r#"# Generated by seekdeep-python-sdk; run ownership and projection execute in Rust.
from __future__ import annotations
import json
import os
import weakref
from dataclasses import asdict, dataclass, field
from typing import Callable
from deepseek_harness_runtime._bridge import Context, invoke
from .client import HarnessClient, _SessionPromptResponse, _release
from .models import InitializeResponse, JsonObject, Notification

_DEFAULTS = json.loads(__DEFAULTS__)

@dataclass(slots=True)
class DeepSeekHarnessConfig:
    provider: str = _DEFAULTS["provider"]
    model: str = _DEFAULTS["model"]
    max_tokens: int | None = _DEFAULTS["max_tokens"]
    cwd: str | None = _DEFAULTS["cwd"]
    runtime_cwd: str | None = _DEFAULTS["runtime_cwd"]
    session_root: str | None = _DEFAULTS["session_root"]
    cordis: str | None = _DEFAULTS["cordis"]
    env: dict[str, str] = field(default_factory=dict)
    runtime_bin: str | None = _DEFAULTS["runtime_bin"]
    launch_args_override: tuple[str, ...] | None = _DEFAULTS["launch_args_override"]
    request_timeout_seconds: float | None = _DEFAULTS["request_timeout_seconds"]
    shutdown_timeout_seconds: float | None = _DEFAULTS["shutdown_timeout_seconds"]
    base_url: str | None = _DEFAULTS["base_url"]
    api_key: str | None = _DEFAULTS["api_key"]

@dataclass(slots=True)
class RunResult:
    session_id: str
    final_response: str
    finish_reason: str | None
    events: list[JsonObject]
    notifications: list[Notification]
    session_root: str | None = None

class DeepSeekHarness:
    """Reusable synchronous SDK backed by a Rust-owned runtime process."""
    def __init__(self, config: DeepSeekHarnessConfig | None = None, **kwargs: object) -> None:
        self._context = Context({
            "config.read":lambda:json.dumps(asdict(self.config),separators=(",",":")),
            "harness.config_from_keywords":lambda value:DeepSeekHarnessConfig(**value),
            "harness.config_asdict":asdict,
            "harness.initialize":lambda value: self._validate_initialize(value),
            "harness.prompt":lambda value:_SessionPromptResponse.model_validate(value).messageId,
        })
        result = invoke({"op":"harness.new",
            "config":None if config is None else self._context.handle(config),
            "keywords":self._context.handle(kwargs),"owner":self._context.identity,
            "seed":list(os.urandom(16))},context=self._context)
        self.config = result["config"]
        self._handle = result["handle"]
        self._finalizer = weakref.finalize(self, _release, self._handle)
        self._client = HarnessClient._from_native(result["client"],result["client_config"])
        self._client.config.runtime_bin = self.config.runtime_bin
        self._client.config.launch_args_override = self.config.launch_args_override
        self._client.config.request_timeout_seconds = self.config.request_timeout_seconds
        self._client.config.shutdown_timeout_seconds = self.config.shutdown_timeout_seconds
    @staticmethod
    def _validate_initialize(value):
        InitializeResponse.model_validate(value)
    @property
    def client(self) -> HarnessClient:
        return self._client
    def _invoke(self, operation, **arguments):
        return invoke({"op":operation,"handle":self._handle,**arguments},context=self._context)
    def __enter__(self) -> "DeepSeekHarness":
        self.start()
        return self
    def __exit__(self, _exc_type, _exc, _tb) -> None:
        self.close()
    def start(self) -> None:
        self._invoke("harness.start")
    def close(self) -> None:
        self._invoke("harness.close")
    def start_session(self, session_id: str | None = None) -> "Session":
        return Session(self,self._invoke("harness.session",session=session_id))
    def run(self, input: str | list[JsonObject], *, session_id: str | None = None,
            on_notification: Callable[[Notification], None] | None = None) -> RunResult:
        return RunResult(**self._invoke("harness.run",session=session_id,input=input,
            observer=None if on_notification is None else self._context.handle(on_notification)))

class Session:
    def __init__(self, harness: DeepSeekHarness, session_id: str) -> None:
        self.harness, self.id = harness, session_id
    def run(self, input: str | list[JsonObject], *,
            on_notification: Callable[[Notification], None] | None = None) -> RunResult:
        return RunResult(**self.harness._invoke("harness.session_run",session=self.id,input=input,
            observer=None if on_notification is None else self.harness._context.handle(on_notification)))

def normalize_input(input: str | list[JsonObject]) -> list[JsonObject]:
    context = Context({})
    return invoke({"op":"api.normalize","value":context.handle(input)},context=context)

def final_response(events: list[JsonObject]) -> str:
    context = Context({})
    return invoke({"op":"api.final_response_object","events":context.handle(events)},context=context)

def finish_reason(events: list[JsonObject]) -> str | None:
    context = Context({})
    return invoke({"op":"api.finish_reason_object","events":context.handle(events)},context=context)

def _is_inbox_receipt(notification: Notification, session_id: str, message_id: str) -> bool:
    return invoke({"op":"api.inbox_receipt","notification":asdict(notification),"session":session_id,"message":message_id})
"#;
