[package]
name = "seekdeep-scope"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
indexmap.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
seekdeep-cordis = { path = "../cordis" }
seekdeep-invariants = { path = "../invariants" }
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
