[package]
name = "seekdeep-jobs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
seekdeep-agent = { path = "../agent" }
seekdeep-cordis = { path = "../cordis" }
seekdeep-core = { path = "../core" }
seekdeep-invariants = { path = "../invariants" }
seekdeep-llm = { path = "../llm" }
seekdeep-util = { path = "../util" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
seekdeep-scope = { path = "../scope" }
tokio.workspace = true

[lints]
workspace = true
