//! Generated Python declarations and byte-buffer marshalling, with SDK decisions in Rust.

use std::collections::BTreeMap;

/// Generates the runtime package's binding modules for one native library basename.
///
/// # Errors
/// Rejects a library name containing directory traversal or path separators.
pub fn runtime_bindings(library_name: &str) -> crate::Result<BTreeMap<String, String>> {
    let mut components = std::path::Path::new(library_name).components();
    if !matches!(components.next(), Some(std::path::Component::Normal(_)))
        || components.next().is_some()
    {
        return Err(crate::Error::new(
            crate::ErrorKind::Value,
            "native binding library must be a basename",
        ));
    }
    let bridge = BRIDGE.replace(
        "__NATIVE_LIBRARY__",
        &serde_json::to_string(library_name)
            .map_err(|error| crate::Error::new(crate::ErrorKind::Value, error.to_string()))?,
    );
    let runtime = RUNTIME
        .replace("__METADATA__", crate::runtime::PACKAGE_METADATA_FILENAME)
        .replace("__MODE_ENV__", crate::runtime::RUNTIME_MODE_ENV_VAR);
    Ok(BTreeMap::from([
        ("__init__.py".to_owned(), runtime),
        ("_bridge.py".to_owned(), bridge),
    ]))
}

const BRIDGE: &str = r#"# Generated by seekdeep-python-sdk; SDK behavior is compiled Rust.
from __future__ import annotations

import ctypes
import itertools
import json
import os
from pathlib import Path

_library = ctypes.CDLL(str(Path(__file__).parent / "runtime" / __NATIVE_LIBRARY__))
_callback_type = ctypes.CFUNCTYPE(ctypes.c_uint64, ctypes.c_uint64, ctypes.c_void_p, ctypes.c_size_t)
_library.seekdeep_python_sdk_abi_version.argtypes = []
_library.seekdeep_python_sdk_abi_version.restype = ctypes.c_uint32
if _library.seekdeep_python_sdk_abi_version() != 1:
    raise ImportError("SeekDeep SDK native binding ABI does not match its Python declarations")
_library.seekdeep_python_sdk_call.argtypes = [ctypes.c_void_p, ctypes.c_size_t, _callback_type, ctypes.c_uint64]
_library.seekdeep_python_sdk_call.restype = ctypes.c_uint64
_library.seekdeep_python_sdk_copy.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
_library.seekdeep_python_sdk_copy.restype = ctypes.c_uint64
_library.seekdeep_python_sdk_buffer_data.argtypes = [ctypes.c_uint64]
_library.seekdeep_python_sdk_buffer_data.restype = ctypes.c_void_p
_library.seekdeep_python_sdk_buffer_length.argtypes = [ctypes.c_uint64]
_library.seekdeep_python_sdk_buffer_length.restype = ctypes.c_size_t
_library.seekdeep_python_sdk_free.argtypes = [ctypes.c_uint64]
_library.seekdeep_python_sdk_free.restype = None

_serial = itertools.count(1)
_active = {}


class _Invocation:
    def __init__(self, objects, callbacks):
        self.objects = dict(enumerate(objects, 1))
        self.callbacks = callbacks

    def retain(self, value):
        key = len(self.objects) + 1
        self.objects[key] = value
        return key

    def invoke(self, operation, arguments):
        if operation == "is_none":
            return self.objects[arguments[0]] is None
        if operation == "equals":
            return bool(self.objects[arguments[0]] == arguments[1])
        if operation == "representation":
            return repr(self.objects[arguments[0]])
        if operation == "environment_object":
            return self.retain(os.environ.get(arguments[0]))
        return self.callbacks[operation](*arguments)


def _exception_message(error):
    try:
        return str(error).encode("ascii", "backslashreplace").decode("ascii")
    except BaseException:
        return type(error).__name__


@_callback_type
def _callback(context, pointer, length):
    invocation = _active.get(context)
    try:
        if invocation is None:
            raise RuntimeError("SeekDeep SDK callback owner is unavailable")
        request = json.loads(ctypes.string_at(pointer, length))
        value = invocation.invoke(request["operation"], request["arguments"])
        payload = json.dumps({"ok": value}, default=os.fspath, separators=(",", ":")).encode("utf-8")
    except BaseException as error:
        if invocation is None:
            envelope = {"error": {"kind": "value", "message": _exception_message(error)}}
        else:
            envelope = {"error": {
                "kind": "foreign",
                "message": _exception_message(error),
                "exception": invocation.retain(error),
                "import_error": isinstance(error, ImportError),
            }}
        payload = json.dumps(envelope, separators=(",", ":")).encode("utf-8")
    return _library.seekdeep_python_sdk_copy(payload, len(payload))


def _exception(details, invocation):
    kind = details["kind"]
    if kind == "foreign":
        error = invocation.objects[details["exception"]]
    elif kind == "os" and details.get("errno") is not None:
        error = OSError(details["errno"], details["message"], details.get("filename"))
    else:
        cls = {"file_not_found": FileNotFoundError, "value": ValueError,
               "type": TypeError, "overflow": OverflowError, "timeout": TimeoutError}.get(kind, RuntimeError)
        error = cls(details["message"])
    if details.get("cause") is not None:
        error.__cause__ = _exception(details["cause"], invocation)
    return error


def invoke(request, objects=(), callbacks=None):
    context = next(_serial)
    invocation = _Invocation(objects, {} if callbacks is None else callbacks)
    _active[context] = invocation
    handle = 0
    try:
        payload = json.dumps(request, default=os.fspath, separators=(",", ":")).encode("utf-8")
        handle = _library.seekdeep_python_sdk_call(payload, len(payload), _callback, context)
        if not handle:
            raise MemoryError("SeekDeep SDK could not allocate its binding response")
        response = json.loads(ctypes.string_at(
            _library.seekdeep_python_sdk_buffer_data(handle),
            _library.seekdeep_python_sdk_buffer_length(handle),
        ))
        if "error" in response:
            raise _exception(response["error"], invocation)
        return response["ok"]
    finally:
        if handle:
            _library.seekdeep_python_sdk_free(handle)
        _active.pop(context, None)
"#;

const RUNTIME: &str = r#"# Generated by seekdeep-python-sdk; runtime selection is compiled Rust.
"""Locate the bundled SeekDeep Harness runtime without downloading or acquiring artifacts."""
from __future__ import annotations

import os
import platform
import shutil
import sys
from pathlib import Path

from ._bridge import invoke as _invoke

PACKAGE_METADATA_FILENAME = "__METADATA__"
RUNTIME_MODE_ENV_VAR = "__MODE_ENV__"


def bundled_package_dir() -> Path:
    return Path(_invoke({"op": "runtime.package", "module": __file__}, callbacks=_callbacks()))


def bundled_default_config_path() -> Path:
    return Path(_invoke({"op": "runtime.default_config"}, callbacks=_callbacks()))


def bundled_runtime_path() -> Path:
    return Path(_invoke({"op": "runtime.executable"}, callbacks=_callbacks()))


def resolve_bundled_launch_args(mode: str | None = None) -> tuple[str, ...]:
    return tuple(_invoke({"op": "runtime.resolve", "mode": 1}, objects=(mode,), callbacks=_callbacks()))


def _current_platform_tag() -> str:
    return _invoke({"op": "runtime.platform", "platform": sys.platform, "machine": platform.machine()})


def _node_launch_args() -> tuple[str, str]:
    return tuple(_invoke({"op": "runtime.node"}, callbacks=_callbacks()))


def _callbacks():
    return {
        "getcwd": lambda: os.getcwd(),
        "runtime.package": lambda: str(bundled_package_dir()),
        "runtime.platform_tag": lambda: _current_platform_tag(),
        "runtime.executable": lambda: str(bundled_runtime_path()),
        "runtime.node": lambda: _node_launch_args(),
        "runtime.find_node": lambda: shutil.which("node"),
    }


__all__ = [
    "PACKAGE_METADATA_FILENAME",
    "RUNTIME_MODE_ENV_VAR",
    "bundled_default_config_path",
    "bundled_package_dir",
    "bundled_runtime_path",
    "resolve_bundled_launch_args",
]
"#;
