//! Source-derived catalog of packages whose invariant installer is empty.

use super::NoopInvariantDescriptor;

/// Every pinned source invariant whose installer is exactly a no-op.
pub const NOOP_INVARIANTS: &[NoopInvariantDescriptor] = &[
    NoopInvariantDescriptor::new(
        "packages/acp/acp/src/invariant.ts",
        "acp-invariant",
        "@seekdeep-ai/seekdeep-acp",
    ),
    NoopInvariantDescriptor::new(
        "packages/boot/app-boot/src/invariant.ts",
        "app-boot-invariant",
        "@seekdeep-ai/seekdeep-app-boot",
    ),
    NoopInvariantDescriptor::new(
        "packages/bundle/base/src/invariant.ts",
        "base-bundle-invariant",
        "@seekdeep-ai/seekdeep-base",
    ),
    NoopInvariantDescriptor::new(
        "packages/bundle/web-app/src/invariant.ts",
        "web-app-invariant",
        "@seekdeep-ai/seekdeep-web-app",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/locale/src/invariant.ts",
        "client-locale-invariant",
        "@seekdeep-ai/seekdeep-client-locale",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/schema-form/src/invariant.ts",
        "client-schema-form-invariant",
        "@seekdeep-ai/seekdeep-client-schema-form",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-agent-preset/src/invariant.ts",
        "client-ui-agent-preset-invariant",
        "@seekdeep-ai/seekdeep-client-ui-agent-preset",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-attachment/src/invariant.ts",
        "client-ui-attachment-invariant",
        "@seekdeep-ai/seekdeep-client-ui-attachment",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-commands/src/invariant.ts",
        "client-ui-commands-invariant",
        "@seekdeep-ai/seekdeep-client-ui-commands",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-conversation/src/invariant.ts",
        "client-ui-conversation-invariant",
        "@seekdeep-ai/seekdeep-client-ui-conversation",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-deliverables/src/invariant.ts",
        "client-ui-deliverables-invariant",
        "@seekdeep-ai/seekdeep-client-ui-deliverables",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-directory-picker-browse/src/invariant.ts",
        "client-ui-directory-picker-browse-invariant",
        "@seekdeep-ai/seekdeep-client-ui-directory-picker-browse",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-directory-picker-native/src/invariant.ts",
        "client-ui-directory-picker-native-invariant",
        "@seekdeep-ai/seekdeep-client-ui-directory-picker-native",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-goal/src/invariant.ts",
        "client-ui-goal-invariant",
        "@seekdeep-ai/seekdeep-client-ui-goal",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-input-trigger/src/invariant.ts",
        "client-ui-input-trigger-invariant",
        "@seekdeep-ai/seekdeep-client-ui-input-trigger",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-jobs/src/invariant.ts",
        "client-ui-jobs-invariant",
        "@seekdeep-ai/seekdeep-client-ui-jobs",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-layout/src/invariant.ts",
        "client-ui-layout-invariant",
        "@seekdeep-ai/seekdeep-client-ui-layout",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-message-feedback/src/invariant.ts",
        "client-ui-feedback-invariant",
        "@seekdeep-ai/seekdeep-client-ui-message-feedback",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-model-selection/src/invariant.ts",
        "client-ui-model-selection-invariant",
        "@seekdeep-ai/seekdeep-client-ui-model-selection",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-permission-presets/src/invariant.ts",
        "client-ui-permission-presets-invariant",
        "@seekdeep-ai/seekdeep-client-ui-permission-presets",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-plan/src/invariant.ts",
        "client-ui-plan-invariant",
        "@seekdeep-ai/seekdeep-client-ui-plan",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-primitives/src/invariant.ts",
        "client-ui-primitives-invariant",
        "@seekdeep-ai/seekdeep-client-ui-primitives",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-settings-general/src/invariant.ts",
        "client-ui-settings-general-invariant",
        "@seekdeep-ai/seekdeep-client-ui-settings-general",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-settings-models/src/invariant.ts",
        "client-ui-settings-models-invariant",
        "@seekdeep-ai/seekdeep-client-ui-settings-models",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-settings-plugin-inventory/src/invariant.ts",
        "client-ui-settings-plugin-inventory-invariant",
        "@seekdeep-ai/seekdeep-client-ui-settings-plugin-inventory",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-settings-plugins/src/invariant.ts",
        "client-ui-settings-plugins-invariant",
        "@seekdeep-ai/seekdeep-client-ui-settings-plugins",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-settings/src/invariant.ts",
        "client-ui-settings-invariant",
        "@seekdeep-ai/seekdeep-client-ui-settings",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-sidebar/src/invariant.ts",
        "client-ui-sidebar-invariant",
        "@seekdeep-ai/seekdeep-client-ui-sidebar",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-skill/src/invariant.ts",
        "client-ui-skill-invariant",
        "@seekdeep-ai/seekdeep-client-ui-skill",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-slots/src/invariant.ts",
        "client-ui-slots-invariant",
        "@seekdeep-ai/seekdeep-client-ui-slots",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-subagent/src/invariant.ts",
        "client-ui-subagent-invariant",
        "@seekdeep-ai/seekdeep-client-ui-subagent",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-theme/src/invariant.ts",
        "client-ui-theme-invariant",
        "@seekdeep-ai/seekdeep-client-ui-theme",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-tool/src/invariant.ts",
        "client-ui-tool-invariant",
        "@seekdeep-ai/seekdeep-client-ui-tool",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-trajectory/src/invariant.ts",
        "client-ui-trajectory-invariant",
        "@seekdeep-ai/seekdeep-client-ui-trajectory",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-user-questions/src/invariant.ts",
        "client-ui-user-questions-invariant",
        "@seekdeep-ai/seekdeep-client-ui-user-questions",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-workflow-run/src/invariant.ts",
        "client-ui-workflow-run-invariant",
        "@seekdeep-ai/seekdeep-client-ui-workflow-run",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/ui-workspace/src/invariant.ts",
        "client-ui-workspace-invariant",
        "@seekdeep-ai/seekdeep-client-ui-workspace",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/web-react/src/invariant.ts",
        "client-web-react-invariant",
        "@seekdeep-ai/seekdeep-client-web-react",
    ),
    NoopInvariantDescriptor::new(
        "packages/client/web/src/invariant.ts",
        "client-web-invariant",
        "@seekdeep-ai/seekdeep-client-web",
    ),
    NoopInvariantDescriptor::new(
        "packages/e2b/e2b/src/invariant.ts",
        "e2b-invariant",
        "@seekdeep-ai/seekdeep-e2b",
    ),
    NoopInvariantDescriptor::new(
        "packages/e2b/fs-e2b/src/invariant.ts",
        "fs-e2b-invariant",
        "@seekdeep-ai/seekdeep-fs-e2b",
    ),
    NoopInvariantDescriptor::new(
        "packages/e2b/subprocess-e2b/src/invariant.ts",
        "subprocess-e2b-invariant",
        "@seekdeep-ai/seekdeep-subprocess-e2b",
    ),
    NoopInvariantDescriptor::new(
        "packages/examples/acp-demo/src/invariant.ts",
        "acp-demo-invariant",
        "@seekdeep-ai/seekdeep-acp-demo",
    ),
    NoopInvariantDescriptor::new(
        "packages/examples/agent-spine-demo/src/invariant.ts",
        "agent-spine-demo-invariant",
        "@seekdeep-ai/seekdeep-agent-spine-demo",
    ),
    NoopInvariantDescriptor::new(
        "packages/examples/jsonrpc-demo/src/invariant.ts",
        "sdk-jsonrpc-demo-invariant",
        "@seekdeep-ai/seekdeep-sdk-jsonrpc-demo",
    ),
    NoopInvariantDescriptor::new(
        "packages/extensions/cordis-client-runner/src/invariant.ts",
        "cordis-client-runner-invariant",
        "@seekdeep-ai/seekdeep-cordis-client-runner",
    ),
    NoopInvariantDescriptor::new(
        "packages/extensions/cordis-host-runner/src/invariant.ts",
        "cordis-host-runner-invariant",
        "@seekdeep-ai/seekdeep-cordis-host-runner",
    ),
    NoopInvariantDescriptor::new(
        "packages/extensions/tool-cordis/src/invariant.ts",
        "tool-cordis-invariant",
        "@seekdeep-ai/seekdeep-tool-cordis",
    ),
    NoopInvariantDescriptor::new(
        "packages/extensions/ui-cordis/src/invariant.ts",
        "client-ui-cordis-invariant",
        "@seekdeep-ai/seekdeep-client-ui-cordis",
    ),
    NoopInvariantDescriptor::new(
        "packages/fs/fs-sandbox/src/invariant.ts",
        "fs-sandbox-invariant",
        "@seekdeep-ai/seekdeep-fs-sandbox",
    ),
    NoopInvariantDescriptor::new(
        "packages/fs/tool-fs-search/src/invariant.ts",
        "tool-fs-search-invariant",
        "@seekdeep-ai/seekdeep-tool-fs-search",
    ),
    NoopInvariantDescriptor::new(
        "packages/fs/tool-str-replace-editor/src/invariant.ts",
        "tool-str-replace-editor-invariant",
        "@seekdeep-ai/seekdeep-tool-str-replace-editor",
    ),
    NoopInvariantDescriptor::new(
        "packages/hooks/hooks-claude-code/src/invariant.ts",
        "hooks-claude-code-invariant",
        "@seekdeep-ai/seekdeep-hooks-claude-code",
    ),
    NoopInvariantDescriptor::new(
        "packages/hooks/hooks-codex/src/invariant.ts",
        "hooks-codex-invariant",
        "@seekdeep-ai/seekdeep-hooks-codex",
    ),
    NoopInvariantDescriptor::new(
        "packages/host/directory-picker-auto/src/invariant.ts",
        "host-directory-picker-auto-invariant",
        "@seekdeep-ai/seekdeep-host-directory-picker-auto",
    ),
    NoopInvariantDescriptor::new(
        "packages/host/directory-picker-browse/src/invariant.ts",
        "host-directory-picker-browse-invariant",
        "@seekdeep-ai/seekdeep-host-directory-picker-browse",
    ),
    NoopInvariantDescriptor::new(
        "packages/host/directory-picker-native/src/invariant.ts",
        "host-directory-picker-native-invariant",
        "@seekdeep-ai/seekdeep-host-directory-picker-native",
    ),
    NoopInvariantDescriptor::new(
        "packages/host/plugin-inventory/src/invariant.ts",
        "host-plugin-inventory-invariant",
        "@seekdeep-ai/seekdeep-host-plugin-inventory",
    ),
    NoopInvariantDescriptor::new(
        "packages/lsp/lsp-stdio/src/invariant.ts",
        "lsp-stdio-invariant",
        "@seekdeep-ai/seekdeep-lsp-stdio",
    ),
    NoopInvariantDescriptor::new(
        "packages/lsp/lsp/src/invariant.ts",
        "lsp-invariant",
        "@seekdeep-ai/seekdeep-lsp",
    ),
    NoopInvariantDescriptor::new(
        "packages/lsp/tool-lsp/src/invariant.ts",
        "tool-lsp-invariant",
        "@seekdeep-ai/seekdeep-tool-lsp",
    ),
    NoopInvariantDescriptor::new(
        "packages/mcp/mcp-client/src/invariant.ts",
        "mcp-client-invariant",
        "@seekdeep-ai/seekdeep-mcp-client",
    ),
    NoopInvariantDescriptor::new(
        "packages/sdk/client/src/invariant.ts",
        "sdk-client-invariant",
        "@seekdeep-ai/seekdeep-sdk-client",
    ),
    NoopInvariantDescriptor::new(
        "packages/sdk/protocol/src/invariant.ts",
        "sdk-protocol-invariant",
        "@seekdeep-ai/seekdeep-sdk-protocol",
    ),
    NoopInvariantDescriptor::new(
        "packages/sdk/server/src/invariant.ts",
        "sdk-jsonrpc-server-invariant",
        "@seekdeep-ai/seekdeep-sdk-jsonrpc-server",
    ),
    NoopInvariantDescriptor::new(
        "packages/session-query/session-log-export/src/invariant.ts",
        "session-export-invariant",
        "@seekdeep-ai/seekdeep-session-log-export",
    ),
    NoopInvariantDescriptor::new(
        "packages/session-query/session-query-sqlite/src/invariant.ts",
        "session-query-sqlite-invariant",
        "@seekdeep-ai/seekdeep-session-query-sqlite",
    ),
    NoopInvariantDescriptor::new(
        "packages/session-query/tool-session-query/src/invariant.ts",
        "tool-session-query-invariant",
        "@seekdeep-ai/seekdeep-tool-session-query",
    ),
    NoopInvariantDescriptor::new(
        "packages/session/session-telemetry-otel/src/invariant.ts",
        "session-telemetry-otel-invariant",
        "@seekdeep-ai/seekdeep-session-telemetry-otel",
    ),
    NoopInvariantDescriptor::new(
        "packages/shell/bash-local/src/invariant.ts",
        "bash-local-invariant",
        "@seekdeep-ai/seekdeep-bash-local",
    ),
    NoopInvariantDescriptor::new(
        "packages/shell/bash-sandbox/src/invariant.ts",
        "bash-sandbox-invariant",
        "@seekdeep-ai/seekdeep-bash-sandbox",
    ),
    NoopInvariantDescriptor::new(
        "packages/shell/pwsh-local/src/invariant.ts",
        "pwsh-local-invariant",
        "@seekdeep-ai/seekdeep-pwsh-local",
    ),
    NoopInvariantDescriptor::new(
        "packages/shell/pwsh-sandbox/src/invariant.ts",
        "pwsh-sandbox-invariant",
        "@seekdeep-ai/seekdeep-pwsh-sandbox",
    ),
    NoopInvariantDescriptor::new(
        "packages/shell/tool-bash-persistent/src/invariant.ts",
        "tool-bash-persistent-invariant",
        "@seekdeep-ai/seekdeep-tool-bash-persistent",
    ),
    NoopInvariantDescriptor::new(
        "packages/shell/tool-bash/src/invariant.ts",
        "tool-bash-invariant",
        "@seekdeep-ai/seekdeep-tool-bash",
    ),
    NoopInvariantDescriptor::new(
        "packages/shell/tool-pwsh/src/invariant.ts",
        "tool-pwsh-invariant",
        "@seekdeep-ai/seekdeep-tool-pwsh",
    ),
    NoopInvariantDescriptor::new(
        "packages/skill/skill-badge/src/invariant.ts",
        "skill-badge-invariant",
        "@seekdeep-ai/seekdeep-skill-badge",
    ),
    NoopInvariantDescriptor::new(
        "packages/skill/skill-filesystem/src/invariant.ts",
        "skill-filesystem-invariant",
        "@seekdeep-ai/seekdeep-skill-filesystem",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/subagent-acp/src/invariant.ts",
        "subagent-acp-invariant",
        "@seekdeep-ai/seekdeep-subagent-acp",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/subagent-claude-code/src/invariant.ts",
        "subagent-claude-code-invariant",
        "@seekdeep-ai/seekdeep-subagent-claude-code",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/subagent-codex/src/invariant.ts",
        "subagent-codex-invariant",
        "@seekdeep-ai/seekdeep-subagent-codex",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/subagent-dsh-sdk/src/invariant.ts",
        "subagent-seekdeep-sdk-invariant",
        "@seekdeep-ai/seekdeep-subagent-seekdeep-sdk",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/subagent-fork-in-process/src/invariant.ts",
        "subagent-fork-in-process-invariant",
        "@seekdeep-ai/seekdeep-subagent-fork-in-process",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/subagent-in-process-driver/src/invariant.ts",
        "subagent-in-process-driver-invariant",
        "@seekdeep-ai/seekdeep-subagent-in-process-driver",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/subagent-spawn-in-process/src/invariant.ts",
        "subagent-spawn-in-process-invariant",
        "@seekdeep-ai/seekdeep-subagent-spawn-in-process",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/tool-subagent-control/src/invariant.ts",
        "tool-subagent-control-invariant",
        "@seekdeep-ai/seekdeep-tool-subagent-control",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/tool-subagent-report/src/invariant.ts",
        "tool-subagent-report-invariant",
        "@seekdeep-ai/seekdeep-tool-subagent-report",
    ),
    NoopInvariantDescriptor::new(
        "packages/subagent/tool-subagent/src/invariant.ts",
        "tool-subagent-invariant",
        "@seekdeep-ai/seekdeep-tool-subagent",
    ),
    NoopInvariantDescriptor::new(
        "packages/terminal/tool-terminal/src/invariant.ts",
        "tool-terminal-invariant",
        "@seekdeep-ai/seekdeep-tool-terminal",
    ),
    NoopInvariantDescriptor::new(
        "packages/test-support/agent-loop-testkit/src/invariant.ts",
        "agent-loop-testkit-invariant",
        "@seekdeep-ai/seekdeep-agent-loop-testkit",
    ),
    NoopInvariantDescriptor::new(
        "packages/test-support/client-runtime/src/invariant.ts",
        "client-test-runtime-invariant",
        "@seekdeep-ai/seekdeep-client-test-runtime",
    ),
    NoopInvariantDescriptor::new(
        "packages/test-support/llm-mock-server/src/invariant.ts",
        "llm-mock-server-invariant",
        "@seekdeep-ai/seekdeep-llm-mock-server",
    ),
    NoopInvariantDescriptor::new(
        "packages/test-support/llm-replay/src/invariant.ts",
        "llm-replay-invariant",
        "@seekdeep-ai/seekdeep-llm-replay",
    ),
    NoopInvariantDescriptor::new(
        "packages/test-support/loader-smoke/src/invariant.ts",
        "loader-smoke-invariant",
        "@seekdeep-ai/seekdeep-loader-smoke",
    ),
    NoopInvariantDescriptor::new(
        "packages/typert/generator/src/invariant.ts",
        "typert-generator-invariant",
        "@seekdeep-ai/seekdeep-typert-generator",
    ),
    NoopInvariantDescriptor::new(
        "packages/typert/loader/src/invariant.ts",
        "typert-loader-invariant",
        "@seekdeep-ai/seekdeep-typert-loader",
    ),
    NoopInvariantDescriptor::new(
        "packages/web/tool-web/src/invariant.ts",
        "tool-web-invariant",
        "@seekdeep-ai/seekdeep-tool-web",
    ),
];
