[package]
name = "seekdeep-invariants"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
parking_lot.workspace = true
regress.workspace = true
serde.workspace = true
serde_json.workspace = true
seekdeep-cordis = { path = "../cordis" }
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
