//! Model-driven runtime reflection, schema, and declaration artifacts.

use indexmap::IndexMap;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use crate::{
    Result, TypertGeneratorError,
    model::{
        DocumentationModel, FaceModel, InvocationModel, InvocationParameterSource,
        InvocationTarget, MemberModel, PackageModel, RemoteBoundaryModel, SymbolId,
        TypeDeclarationModel, TypeNodeKind, TypertFace,
    },
    remote,
    renderer::TypeGraphRenderer,
    schema::{
        SchemaArtifact, SchemaEmitter, context_key, invocation_roots, parameter_key, result_key,
    },
    text::{indent, locale_compare, quote, utf16_compare},
};

const GENERATED: &str =
    "/* Generated by @seekdeep-ai/seekdeep-typert-generator from FaceModel — do not edit. */";
const REMOTE_GENERATED: &str = "/* Generated by @seekdeep-ai/seekdeep-typert-generator from the Host FaceModel — do not edit. */";

/// JavaScript and declaration artifacts for one package face.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModelEmitResult {
    /// Modeled package identity.
    pub package: String,
    /// Independently compiled face.
    pub face: TypertFace,
    /// Public schema exports in source order.
    pub exports: Vec<String>,
    /// Runtime contribution module.
    pub js: String,
    /// Public declarations.
    pub dts: String,
    /// Optional Host-for-Client Remote contribution.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remote: Option<RemoteModelEmitResult>,
}

/// Host-for-Client Remote contribution and source-linked declarations.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RemoteModelEmitResult {
    /// Strict Remote runtime descriptors.
    pub js: String,
    /// Typed Client contract.
    pub dts: String,
    /// Declaration source map.
    pub dts_map: String,
}

/// Artifact emitter bound to one independently analyzed face.
pub struct FaceModelEmitter<'a> {
    face: &'a FaceModel,
    renderer: TypeGraphRenderer<'a>,
}

impl<'a> FaceModelEmitter<'a> {
    /// Creates an emitter without retaining compiler objects or registry state.
    pub fn new(face: &'a FaceModel) -> Self {
        Self {
            face,
            renderer: TypeGraphRenderer::new(&face.graph),
        }
    }

    /// Emits one exact modeled package, including Remote artifacts on the Host face.
    ///
    /// # Errors
    /// Rejects missing packages, broken graph edges, and unsupported schema projections.
    pub fn emit(&self, package_name: &str) -> Result<ModelEmitResult> {
        let package = self
            .face
            .packages
            .iter()
            .find(|package| package.name == package_name)
            .ok_or_else(|| {
                TypertGeneratorError::Emit(format!(
                    "typert emitter({}): package {package_name} is not modeled on this face",
                    self.face.face.as_str()
                ))
            })?;
        let schemas = SchemaEmitter::new(
            &self.renderer,
            &package.schemas,
            invocation_roots(&package.invocations),
        )?
        .emit()?;
        let runtime = self.runtime_model(package)?;
        Ok(ModelEmitResult {
            package: package_name.to_owned(),
            face: self.face.face,
            exports: package
                .schemas
                .iter()
                .map(|schema| schema.export.name.clone())
                .collect(),
            js: self.render_js(package, &schemas, &runtime)?,
            dts: Self::render_dts(package, &schemas),
            remote: if self.face.face == TypertFace::Host && !package.invocations.is_empty() {
                Some(self.emit_remote(package)?)
            } else {
                None
            },
        })
    }

    fn runtime_model(&self, package: &PackageModel) -> Result<Value> {
        let services = package.services.iter().map(|service| {
            let members = service.members.iter().map(|id| self.runtime_member(self.renderer.member(id)?)).collect::<Result<Vec<_>>>()?;
            let mut value = documentation_literal(&service.documentation);
            extend(&mut value, json!({ "key": service.key, "exportName": service.export.name, "members": members,
                "types": self.runtime_types(self.renderer.declaration_closure_for_members(&service.members)?, &service.symbol)? }));
            Ok(value)
        }).collect::<Result<Vec<_>>>()?;
        let events = package
            .events
            .iter()
            .map(|event| {
                let node = self.renderer.defined_node(&event.signature)?;
                let TypeNodeKind::Function { signature } = &node.kind else {
                    return Err(TypertGeneratorError::Emit(format!(
                        "typert emitter({}): event {} is not a function type",
                        self.face.face.as_str(),
                        event.name
                    )));
                };
                let mut value = documentation_literal(&event.documentation);
                value["name"] = json!(event.name);
                if let Some(mode) = &event.mode {
                    value["mode"] = json!(mode);
                }
                value["signature"] = json!(format!(
                    "{}{}",
                    quote(&event.name),
                    self.renderer.render_signature(signature, None)?
                ));
                Ok(value)
            })
            .collect::<Result<Vec<_>>>()?;
        let objects = package.objects.iter().map(|object| {
            let declaration = self.renderer.declaration(&object.symbol)?;
            let member_ids = declaration.members.iter().map(MemberModel::id).collect::<Vec<_>>();
            let members = declaration.members.iter().map(|member| self.runtime_member(member)).collect::<Result<Vec<_>>>()?;
            let mut value = documentation_literal(&object.documentation);
            extend(&mut value, json!({ "name": declaration.name, "exportName": object.export.name, "members": members,
                "types": self.runtime_types(self.renderer.declaration_closure_for_members(&member_ids)?, &declaration.id)? }));
            Ok(value)
        }).collect::<Result<Vec<_>>>()?;
        Ok(json!({ "services": services, "events": events, "objects": objects }))
    }

    fn runtime_member(&self, member: &MemberModel) -> Result<Value> {
        let MemberModel::Defined(defined) = member else {
            return Err(TypertGeneratorError::Render(format!(
                "unsupported model variant {}",
                serde_json::to_string(member).expect("member records serialize")
            )));
        };
        let mut value = json!({ "kind": defined.kind.as_str(), "name": defined.base.name, "signature": self.renderer.render_member(member, true, None)? });
        if let Some(summary) = &defined.base.documentation.summary {
            value["summary"] = json!(summary);
        }
        if let Some(js_doc) = &defined.base.documentation.js_doc {
            value["jsDoc"] = json!(js_doc);
        }
        Ok(value)
    }

    fn runtime_types(
        &self,
        declarations: Vec<&TypeDeclarationModel>,
        root: &SymbolId,
    ) -> Result<Vec<Value>> {
        let mut values = declarations
            .into_iter()
            .filter(|declaration| declaration.id != *root)
            .map(|declaration| Ok(json!({ "name": declaration.name, "declaration": self.renderer.render_declaration(&declaration.id)? })))
            .collect::<Result<Vec<_>>>()?;
        values.sort_by(|left, right| {
            locale_compare(
                left["name"].as_str().expect("type name"),
                right["name"].as_str().expect("type name"),
            )
        });
        Ok(values)
    }

    fn render_js(
        &self,
        package: &PackageModel,
        schemas: &SchemaArtifact<'_>,
        runtime: &Value,
    ) -> Result<String> {
        let mut lines = schema_prelude(GENERATED, schemas);
        for schema in &schemas.exports {
            lines.push(format!(
                "export const {} = {}",
                schema.export_name, schema.internal_name
            ));
        }
        if !schemas.exports.is_empty() {
            lines.push(String::new());
        }
        lines.push("export const TYPERT = {".to_owned());
        lines.push(format!("  package: {},", quote(&package.name)));
        lines.push(format!("  face: {},", quote(self.face.face.as_str())));
        lines.push("  schemas: [".to_owned());
        for schema in &schemas.exports {
            lines.push(format!(
                "    {{ name: {}, schema: {} }},",
                quote(&schema.export_name),
                schema.export_name
            ));
        }
        lines.extend(["  ],".to_owned(), "  invocations: [".to_owned()]);
        for invocation in &package.invocations {
            lines.push(format!(
                "{},",
                indent(&invocation_literal(invocation, schemas)?, 4)
            ));
        }
        lines.push("  ],".to_owned());
        let model =
            serde_json::to_string_pretty(runtime).expect("runtime reflection contains JSON values");
        lines.push(format!("  model: {},", indent(&model, 2).trim_start()));
        lines.push("}".to_owned());
        Ok(format!("{}\n", lines.join("\n")))
    }

    fn render_dts(package: &PackageModel, schemas: &SchemaArtifact<'_>) -> String {
        let mut imports = IndexMap::<String, Vec<String>>::new();
        for schema in &schemas.exports {
            let subpath = &schema.model.export.subpath;
            let specifier = if subpath == "." {
                package.name.clone()
            } else {
                format!(
                    "{}{}",
                    package.name,
                    subpath.chars().skip(1).collect::<String>()
                )
            };
            imports.entry(specifier).or_default().push(format!(
                "{} as {}$source",
                schema.model.export.name, schema.export_name
            ));
        }
        let mut lines = vec![GENERATED.to_owned()];
        if !schemas.exports.is_empty() {
            lines.push("import type { z } from 'zod'".to_owned());
        }
        let mut imports = imports.into_iter().collect::<Vec<_>>();
        imports.sort_by(|(left, _), (right, _)| locale_compare(left, right));
        for (specifier, mut names) in imports {
            names.sort_by(|left, right| utf16_compare(left, right));
            lines.push(format!(
                "import type {{ {} }} from {}",
                names.join(", "),
                quote(&specifier)
            ));
        }
        lines.push(String::new());
        for schema in &schemas.exports {
            lines.push(format!(
                "export declare const {}: z.ZodType<{}$source>",
                schema.export_name, schema.export_name
            ));
        }
        if !schemas.exports.is_empty() {
            lines.push(String::new());
        }
        lines.push("export declare const TYPERT: unknown".to_owned());
        format!("{}\n", lines.join("\n"))
    }

    fn emit_remote(&self, package: &PackageModel) -> Result<RemoteModelEmitResult> {
        let schemas =
            SchemaEmitter::new(&self.renderer, &[], invocation_roots(&package.invocations))?
                .emit()?;
        let mut lines = schema_prelude(REMOTE_GENERATED, &schemas);
        lines.push("export const TYPERT_REMOTE = {".to_owned());
        lines.push(format!("  package: {},", quote(&package.name)));
        lines.push("  descriptors: [".to_owned());
        for invocation in &package.invocations {
            lines.push(format!(
                "{},",
                indent(&invocation_literal(invocation, &schemas)?, 4)
            ));
        }
        lines.extend([
            "  ],".to_owned(),
            "}".to_owned(),
            String::new(),
            "export default TYPERT_REMOTE".to_owned(),
        ]);
        let (dts, dts_map) = remote::declarations(&self.renderer, package, REMOTE_GENERATED)?;
        Ok(RemoteModelEmitResult {
            js: format!("{}\n", lines.join("\n")),
            dts,
            dts_map,
        })
    }
}

fn schema_prelude(banner: &str, schemas: &SchemaArtifact<'_>) -> Vec<String> {
    let mut lines = vec![banner.to_owned()];
    if !schemas.definitions.is_empty() {
        lines.extend(["import { z } from 'zod'".to_owned(), String::new()]);
    }
    lines.extend(schemas.definitions.clone());
    if !schemas.definitions.is_empty() {
        lines.push(String::new());
    }
    lines
}

fn documentation_literal(documentation: &DocumentationModel) -> Value {
    serde_json::to_value(documentation).expect("documentation contains JSON values")
}

fn extend(value: &mut Value, fields: Value) {
    let Value::Object(fields) = fields else {
        unreachable!("reflection fields are objects");
    };
    value
        .as_object_mut()
        .expect("reflection object")
        .extend(fields);
}

fn strict_codec(boundary: &RemoteBoundaryModel, schema: &str) -> String {
    format!(
        "{{\n  mode: 'strict',\n  typeSymbol: {},\n  schema: {schema},\n}}",
        quote(boundary.type_symbol.as_str())
    )
}

fn invocation_literal(
    invocation: &InvocationModel,
    schemas: &SchemaArtifact<'_>,
) -> Result<String> {
    let mut lines = vec![
        "{".to_owned(),
        format!("  id: {},", quote(invocation.id.as_str())),
        format!("  service: {},", quote(&invocation.service)),
        format!("  namespace: {},", quote(&invocation.namespace)),
        format!("  method: {},", quote(&invocation.method)),
    ];
    if let Some(implementation) = &invocation.implementation {
        lines.push(format!("  implementation: {},", quote(implementation)));
    }
    match &invocation.invocation {
        InvocationTarget::Direct => lines.push("  invocation: { kind: 'direct' },".to_owned()),
        InvocationTarget::Context {
            context,
            wire,
            boundary,
        } => {
            lines.extend([
                "  invocation: {".to_owned(),
                "    kind: 'context',".to_owned(),
                format!("    context: {},", quote(context)),
                format!("    wire: {},", quote(wire)),
                format!(
                    "    codec: {},",
                    indent(
                        &strict_codec(boundary, schemas.boundary(&context_key(invocation))?),
                        4
                    )
                    .trim_start()
                ),
                "  },".to_owned(),
            ]);
        }
    }
    if let Some(scope) = &invocation.scope {
        lines.extend([
            "  scope: {".to_owned(),
            format!("    context: {},", quote(&scope.context)),
            format!("    wire: {},", quote(&scope.wire)),
            "  },".to_owned(),
        ]);
    }
    lines.push("  parameters: [".to_owned());
    for (index, parameter) in invocation.parameters.iter().enumerate() {
        lines.extend([
            "    {".to_owned(),
            format!("      name: {},", quote(&parameter.name)),
            format!("      wire: {},", quote(&parameter.wire)),
            format!(
                "      source: {},",
                quote(match parameter.source {
                    InvocationParameterSource::Json => "json",
                    InvocationParameterSource::Lookup => "lookup",
                })
            ),
        ]);
        if let Some(lookup) = &parameter.lookup {
            lines.push(format!("      lookup: {},", quote(lookup)));
        }
        if parameter.boundary.accepts_undefined {
            lines.push("      acceptsUndefined: true,".to_owned());
        }
        lines.push(format!(
            "      codec: {},",
            indent(
                &strict_codec(
                    &parameter.boundary,
                    schemas.boundary(&parameter_key(invocation, index))?
                ),
                6
            )
            .trim_start()
        ));
        lines.push("    },".to_owned());
    }
    lines.push("  ],".to_owned());
    if invocation.cancellation.is_some() {
        lines.push("  cancellation: { parameter: 'signal' },".to_owned());
    }
    lines.push(format!(
        "  result: {},",
        indent(
            &strict_codec(
                &invocation.result,
                schemas.boundary(&result_key(invocation))?
            ),
            2
        )
        .trim_start()
    ));
    lines.push(format!(
        "  sourceLocation: {},",
        serde_json::to_string(&invocation.location).expect("source coordinates serialize")
    ));
    lines.push("}".to_owned());
    Ok(lines.join("\n"))
}
