//! Generates the npm entry of `@seekdeep-ai/seekdeep`.
//!
//! The package manifest maps the `seekdeep` command to `lib/bin.js`. The source shipped
//! its whole CLI there as one ESM bundle; the port's CLI is the compiled Rust
//! `seekdeep` executable, so the npm entry is a launcher that only locates that
//! executable and runs it: `SEEKDEEP_EXECUTABLE` names one explicitly, otherwise the
//! platform package `@seekdeep-ai/seekdeep-<platform>-<arch>` installed next to the
//! package provides `bin/seekdeep`. Arguments, standard streams, the exit status, and
//! termination signals pass through unchanged. Without an executable the launcher
//! answers only `--version` from its own manifest (the source printed the manifest
//! version from JavaScript as well) and otherwise fails with the resolution it tried.

use std::path::{Path, PathBuf};

/// Package directory of the CLI relative to the workspace root.
const PACKAGE_DIRECTORY: &str = "apps/cli";

/// Launcher path relative to the package directory (the manifest's `bin` target).
const LAUNCHER: &str = "lib/bin.js";

/// Environment variable naming an explicit executable.
#[cfg(test)]
const EXECUTABLE_ENV: &str = "SEEKDEEP_EXECUTABLE";

/// Prefix of the platform packages carrying the compiled executable.
#[cfg(test)]
const PLATFORM_PACKAGE_PREFIX: &str = "@seekdeep-ai/seekdeep-";

const SOURCE: &str = r"#!/usr/bin/env node
// Generated by `cargo xtask build-client`; do not edit.
//
// The SeekDeep Harness CLI is the compiled Rust `seekdeep` executable. This npm entry
// only locates it and runs it: SEEKDEEP_EXECUTABLE names one explicitly, otherwise the
// platform package @seekdeep-ai/seekdeep-<platform>-<arch> installed next to this
// package provides bin/seekdeep. Without an executable only `--version` is answered,
// from this package's own manifest.
import { spawn } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { constants as osConstants } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const EXECUTABLE_ENV = 'SEEKDEEP_EXECUTABLE'
const PLATFORM_PACKAGE = `@seekdeep-ai/seekdeep-${process.platform}-${process.arch}`
const EXECUTABLE_NAME = process.platform === 'win32' ? 'seekdeep.exe' : 'seekdeep'

function manifestVersion() {
  const manifest = JSON.parse(
    readFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'package.json'), 'utf8'),
  )
  return typeof manifest.version === 'string' ? manifest.version : '0.0.0'
}

function resolveExecutable() {
  const explicit = process.env[EXECUTABLE_ENV]
  if (explicit) return { path: explicit, source: EXECUTABLE_ENV }
  let manifest
  try {
    manifest = createRequire(import.meta.url).resolve(`${PLATFORM_PACKAGE}/package.json`)
  } catch {
    return null
  }
  const path = join(dirname(manifest), 'bin', EXECUTABLE_NAME)
  return existsSync(path) ? { path, source: PLATFORM_PACKAGE } : null
}

const args = process.argv.slice(2)
const executable = resolveExecutable()
if (executable === null) {
  if (args.length === 1 && (args[0] === '--version' || args[0] === '-V')) {
    process.stdout.write(`${manifestVersion()}\n`)
    process.exit(0)
  }
  process.stderr.write(
    `seekdeep: no compiled executable for ${process.platform}-${process.arch}: install ` +
      `${PLATFORM_PACKAGE} next to @seekdeep-ai/seekdeep or set ${EXECUTABLE_ENV} to a seekdeep executable\n`,
  )
  process.exit(1)
}

const child = spawn(executable.path, args, { stdio: 'inherit', windowsHide: true })
for (const signal of ['SIGINT', 'SIGTERM', 'SIGHUP']) {
  process.on(signal, () => {
    child.kill(signal)
  })
}
child.on('error', (error) => {
  process.stderr.write(`seekdeep: cannot start ${executable.path} (${executable.source}): ${error.message}\n`)
  process.exit(1)
})
child.on('exit', (code, signal) => {
  if (signal !== null) process.exit(128 + (osConstants.signals[signal] ?? 0))
  process.exit(code ?? 1)
})
";

/// Writes the launcher under the workspace root when its content changed and returns
/// its path.
///
/// # Errors
///
/// Returns filesystem failures.
pub(super) fn write(workspace_root: &Path) -> anyhow::Result<PathBuf> {
    let path = workspace_root.join(PACKAGE_DIRECTORY).join(LAUNCHER);
    write_to(&path)?;
    Ok(path)
}

fn write_to(path: &Path) -> anyhow::Result<()> {
    if std::fs::read_to_string(path).is_ok_and(|current| current == SOURCE) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, SOURCE)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::{path::Path, process::Command};

    use super::{EXECUTABLE_ENV, LAUNCHER, PLATFORM_PACKAGE_PREFIX, SOURCE, write_to};

    fn node() -> Option<std::path::PathBuf> {
        let output = Command::new("node").arg("--version").output().ok()?;
        output.status.success().then(|| "node".into())
    }

    fn package(root: &Path) -> std::path::PathBuf {
        let package = root.join("apps/cli");
        std::fs::create_dir_all(&package).unwrap();
        std::fs::write(
            package.join("package.json"),
            "{\"name\":\"@seekdeep-ai/seekdeep\",\"version\":\"9.9.9-launcher\"}\n",
        )
        .unwrap();
        let launcher = package.join(LAUNCHER);
        write_to(&launcher).unwrap();
        launcher
    }

    #[test]
    fn the_launcher_is_written_once_and_names_its_resolution_inputs() {
        let temporary = tempfile::tempdir().unwrap();
        let launcher = package(temporary.path());
        assert!(SOURCE.contains(EXECUTABLE_ENV));
        assert!(SOURCE.contains(PLATFORM_PACKAGE_PREFIX));
        assert!(SOURCE.starts_with("#!/usr/bin/env node\n"));
        let first = std::fs::metadata(&launcher).unwrap().modified().unwrap();
        write_to(&launcher).unwrap();
        assert_eq!(
            std::fs::metadata(&launcher).unwrap().modified().unwrap(),
            first
        );
    }

    #[test]
    fn without_an_executable_only_the_manifest_version_is_answered() {
        let Some(node) = node() else {
            eprintln!("skipping: node is not installed");
            return;
        };
        let temporary = tempfile::tempdir().unwrap();
        let launcher = package(temporary.path());
        let version = Command::new(&node)
            .arg(&launcher)
            .arg("--version")
            .env_remove(EXECUTABLE_ENV)
            .output()
            .unwrap();
        assert!(version.status.success());
        assert_eq!(String::from_utf8_lossy(&version.stdout), "9.9.9-launcher\n");
        let refused = Command::new(&node)
            .arg(&launcher)
            .arg("web")
            .env_remove(EXECUTABLE_ENV)
            .output()
            .unwrap();
        assert_eq!(refused.status.code(), Some(1));
        let stderr = String::from_utf8_lossy(&refused.stderr);
        assert!(stderr.contains(PLATFORM_PACKAGE_PREFIX), "{stderr}");
        assert!(stderr.contains(EXECUTABLE_ENV), "{stderr}");
    }

    #[cfg(unix)]
    fn fake_executable(path: &Path) {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, "#!/bin/sh\nprintf 'ran:%s\\n' \"$*\"\nexit 7\n").unwrap();
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn the_explicit_executable_receives_the_arguments_and_owns_the_exit_status() {
        let Some(node) = node() else {
            eprintln!("skipping: node is not installed");
            return;
        };
        let temporary = tempfile::tempdir().unwrap();
        let launcher = package(temporary.path());
        let executable = temporary.path().join("fake/seekdeep");
        fake_executable(&executable);
        let output = Command::new(&node)
            .arg(&launcher)
            .args(["--version", "web", "--port", "3000"])
            .env(EXECUTABLE_ENV, &executable)
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(7));
        assert_eq!(
            String::from_utf8_lossy(&output.stdout),
            "ran:--version web --port 3000\n"
        );
    }

    #[cfg(unix)]
    #[test]
    fn the_platform_package_next_to_the_launcher_provides_the_executable() {
        let Some(node) = node() else {
            eprintln!("skipping: node is not installed");
            return;
        };
        let temporary = tempfile::tempdir().unwrap();
        let launcher = package(temporary.path());
        let platform = format!(
            "{PLATFORM_PACKAGE_PREFIX}{}-{}",
            node_platform(),
            node_arch()
        );
        let package = temporary.path().join("node_modules").join(&platform);
        std::fs::create_dir_all(&package).unwrap();
        std::fs::write(
            package.join("package.json"),
            format!("{{\"name\":\"{platform}\",\"version\":\"9.9.9-launcher\"}}\n"),
        )
        .unwrap();
        fake_executable(&package.join("bin/seekdeep"));
        let output = Command::new(&node)
            .arg(&launcher)
            .arg("--version")
            .env_remove(EXECUTABLE_ENV)
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(7), "{output:?}");
        assert_eq!(String::from_utf8_lossy(&output.stdout), "ran:--version\n");
    }

    #[cfg(unix)]
    fn node_platform() -> &'static str {
        match std::env::consts::OS {
            "macos" => "darwin",
            other => other,
        }
    }

    #[cfg(unix)]
    fn node_arch() -> &'static str {
        match std::env::consts::ARCH {
            "x86_64" => "x64",
            "aarch64" => "arm64",
            other => other,
        }
    }
}
