//! Reproducible Node-only installer binding containing compiled Rust behavior.

use std::{
    path::{Path, PathBuf},
    process::Command,
};

use base64::Engine as _;

const PACKAGE: &str = "seekdeep-subprocess-postinstall";
const ARTIFACT: &str = "seekdeep_subprocess_postinstall";
const ENTRY: &str = "packages/subprocess/subprocess-local/scripts/ensure-spawn-helper.mjs";

pub(super) fn run(metadata: &super::CargoMetadata, check: bool) -> anyhow::Result<()> {
    let target = metadata
        .target_directory
        .join("xtask/subprocess-postinstall");
    let mut flags = vec![format!(
        "--remap-path-prefix={}=/seekdeep",
        metadata.workspace_root.display()
    )];
    let cargo_home = std::env::var_os("CARGO_HOME")
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var_os("HOME")
                .or_else(|| std::env::var_os("USERPROFILE"))
                .map(|home| PathBuf::from(home).join(".cargo"))
        });
    if let Some(cargo_home) = cargo_home {
        flags.push(format!(
            "--remap-path-prefix={}=/cargo",
            cargo_home.display()
        ));
    }
    let mut command = Command::new("cargo");
    command
        .current_dir(&metadata.workspace_root)
        .env("CARGO_TARGET_DIR", &target)
        .env("CARGO_INCREMENTAL", "0")
        .env("CARGO_BUILD_JOBS", "2")
        .env("CARGO_PROFILE_RELEASE_DEBUG", "0")
        .env("CARGO_PROFILE_RELEASE_STRIP", "symbols")
        .env("CARGO_ENCODED_RUSTFLAGS", flags.join("\u{1f}"))
        .args([
            "build",
            "--locked",
            "--release",
            "--target",
            "wasm32-unknown-unknown",
            "--package",
            PACKAGE,
            "--lib",
        ]);
    anyhow::ensure!(command.status()?.success(), "postinstall Rust build failed");
    let staging = tempfile::tempdir()?;
    let status = Command::new("wasm-bindgen")
        .arg(
            target
                .join("wasm32-unknown-unknown/release")
                .join(format!("{ARTIFACT}.wasm")),
        )
        .args([
            "--target",
            "nodejs",
            "--out-name",
            "postinstall",
            "--no-typescript",
            "--remove-name-section",
            "--remove-producers-section",
            "--out-dir",
        ])
        .arg(staging.path())
        .status()
        .map_err(super::wasm_bindgen_launch_error)?;
    anyhow::ensure!(status.success(), "postinstall binding generation failed");
    let bindings = std::fs::read_to_string(staging.path().join("postinstall.js"))?;
    let bytes = std::fs::read(staging.path().join("postinstall_bg.wasm"))?;
    let script = embed(&bindings, &bytes)?;
    let output = metadata.workspace_root.join(ENTRY);
    if check {
        anyhow::ensure!(
            std::fs::read_to_string(&output)? == script,
            "stale subprocess postinstall binding; run cargo xtask subprocess-postinstall"
        );
    } else {
        std::fs::create_dir_all(output.parent().unwrap_or(Path::new(".")))?;
        std::fs::write(&output, script)?;
    }
    println!(
        "subprocess postinstall Rust binding {}: {ENTRY}",
        if check { "verified" } else { "written" }
    );
    Ok(())
}

fn embed(bindings: &str, wasm: &[u8]) -> anyhow::Result<String> {
    const READ: &str = "const wasmBytes = require('fs').readFileSync(wasmPath);";
    anyhow::ensure!(
        bindings.matches(READ).count() == 1
            && bindings
                .lines()
                .filter(|line| line.starts_with("const wasmPath = "))
                .count()
                == 1,
        "unsupported wasm-bindgen Node initialization"
    );
    let encoded = base64::engine::general_purpose::STANDARD.encode(wasm);
    let bindings = bindings
        .lines()
        .filter(|line| !line.starts_with("const wasmPath = "))
        .collect::<Vec<_>>()
        .join("\n")
        .replace(
            READ,
            &format!("const wasmBytes = Buffer.from('{encoded}', 'base64');"),
        );
    Ok(format!(
        "/** Generated by cargo xtask subprocess-postinstall from compiled Rust. */\n\
         import {{ createRequire }} from 'node:module';\n\
         const require = createRequire(import.meta.url);\n\
         const exports = Object.create(null);\n\
         {bindings}\n\
         exports.ensureNodePtySpawnHelpers(import.meta.resolve('node-pty'), process.platform, process.arch);\n"
    ))
}
