[package]
name = "seekdeep-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
indexmap.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
seekdeep-cordis = { path = "../cordis" }
seekdeep-llm = { path = "../llm" }
seekdeep-scope = { path = "../scope" }
seekdeep-typert-protocol = { path = "../typert-protocol" }
seekdeep-typert-registry = { path = "../typert-registry" }
seekdeep-util = { path = "../util" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
seekdeep-invariants = { path = "../invariants" }

[lints]
workspace = true
