[package]
name = "seekdeep-command-feedback"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
seekdeep-anonymous-user-id = { path = "../anonymous-user-id" }
seekdeep-commands = { path = "../commands" }
seekdeep-cordis = { path = "../cordis" }
seekdeep-core = { path = "../core" }
seekdeep-invariants = { path = "../invariants" }
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
