[package]
name = "seekdeep-client-ui-directory-picker-browse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Portable and Rust/WASM in-app directory browser"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
seekdeep-cordis = { path = "../cordis" }

[lints]
workspace = true
