[package]
name = "seekdeep-plan-mode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
parking_lot.workspace = true
regex.workspace = true
seekdeep-cordis = { path = "../cordis" }
seekdeep-core = { path = "../core" }
seekdeep-invariants = { path = "../invariants" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
